# Funding links shown in the Sponsor button on GitHub
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: QorvenAI
ko_fi: qorvenai
custom:
  - https://qorven.ai/sponsor
