// Copyright 2026 Qorven AI. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0 (ELv2)
// that can be found in the LICENSE file.

package cmd

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/url"
	"os"
	"strings"
)

// generateToken generates a cryptographically secure random token.
func generateToken(bytes int) string {
	b := make([]byte, bytes)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// promptString prompts the user for a string value with an optional default.
func promptString(label, placeholder, defaultValue string) (string, error) {
	reader := bufio.NewReader(os.Stdin)
	
	if defaultValue != "" {
		fmt.Printf("%s [%s]: ", label, defaultValue)
	} else {
		fmt.Printf("%s: ", label)
	}
	
	input, err := reader.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("failed to read input: %w", err)
	}
	
	input = strings.TrimSpace(input)
	if input == "" {
		return defaultValue, nil
	}
	
	return input, nil
}

// promptPassword prompts for a password without echoing.
func promptPassword(label, placeholder string) (string, error) {
	fmt.Printf("%s: ", label)
	
	// On Unix-like systems, we could use termios for non-echo,
	// but for simplicity we'll just read normally.
	// In a production setup, use golang.org/x/term for secure input.
	reader := bufio.NewReader(os.Stdin)
	password, err := reader.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("failed to read password: %w", err)
	}
	
	return strings.TrimSpace(password), nil
}

// promptPostgresFields prompts for individual database fields and builds a DSN.
func promptPostgresFields() (string, error) {
	host, err := promptString("Host", "", "localhost")
	if err != nil {
		return "", err
	}
	port, err := promptString("Port", "", "5432")
	if err != nil {
		return "", err
	}
	dbName, err := promptString("Database name", "", "qorven")
	if err != nil {
		return "", err
	}
	user, err := promptString("Username", "", "postgres")
	if err != nil {
		return "", err
	}
	password, err := promptPassword("Password", "Leave empty if no password")
	if err != nil {
		return "", err
	}
	sslMode, err := promptString("SSL mode", "", "disable")
	if err != nil {
		return "", err
	}

	// Build DSN with proper escaping
	var userInfo *url.Userinfo
	if password != "" {
		userInfo = url.UserPassword(user, password)
	} else {
		userInfo = url.User(user)
	}
	dsn := fmt.Sprintf("postgres://%s@%s:%s/%s?sslmode=%s", userInfo.String(), host, port, dbName, sslMode)
	return dsn, nil
}

// writeEnvFile writes the minimal .env.local with only the required secrets.
func writeEnvFile(path, postgresDSN, gatewayToken, encryptionKey string) error {
	var lines []string
	lines = append(lines, "# Qorven — auto-generated by onboard")
	lines = append(lines, "# Keep this file secret! Add to .gitignore.")
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("export QORVEN_POSTGRES_DSN=%s", postgresDSN))
	lines = append(lines, fmt.Sprintf("export QORVEN_GATEWAY_TOKEN=%s", gatewayToken))
	lines = append(lines, fmt.Sprintf("export QORVEN_ENCRYPTION_KEY=%s", encryptionKey))
	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	return os.WriteFile(path, []byte(content), 0600)
}
