ALTER TABLE social_integrations
  ADD COLUMN IF NOT EXISTS nickname   TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS avatar_url TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS post_hours JSONB   NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS post_days  JSONB   NOT NULL DEFAULT '[0,1,2,3,4,5,6]',
  ADD COLUMN IF NOT EXISTS group_name TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS paused     BOOLEAN NOT NULL DEFAULT false;
