DROP TABLE IF EXISTS sla_measurements;
DROP TABLE IF EXISTS sla_definitions;
DROP TABLE IF EXISTS capacity_forecasts;
DROP TABLE IF EXISTS asset_library;
DROP TABLE IF EXISTS sod_rules;
DROP TABLE IF EXISTS exceptions;
DROP TABLE IF EXISTS task_state_transitions;
DROP TABLE IF EXISTS policy_events;
DROP TABLE IF EXISTS policies;
DROP TABLE IF EXISTS approval_requests;
DROP TABLE IF EXISTS approval_matrix;
DROP TABLE IF EXISTS skill_families;
DROP TABLE IF EXISTS designations;
ALTER TABLE tasks DROP COLUMN IF EXISTS workflow_state;
ALTER TABLE tasks DROP COLUMN IF EXISTS state_changed_at;
ALTER TABLE tasks DROP COLUMN IF EXISTS state_changed_by;
ALTER TABLE tasks DROP COLUMN IF EXISTS blocked_reason;
ALTER TABLE tasks DROP COLUMN IF EXISTS requires_approval;
ALTER TABLE tasks DROP COLUMN IF EXISTS approval_request_id;
