'use client';

// Copyright 2026 Qorven AI. Licensed under Elastic License 2.0 (ELv2).

/**
 * /scenarios — scenario lab (T2.7).
 *
 * A scenario is a persistent "Project": seed (premise) + agent_count +
 * rounds. Running one triggers an async multi-agent simulation; the
 * round log + final report appear when it finishes. We poll every 2s
 * while status === "running".
 *
 * Layout: list rail (left), selected scenario detail (right). Create
 * form lives inline in the rail.
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  FlaskConical, Plus, Play, Loader2, CheckCircle2, XCircle, Clock,
  RefreshCw, MessageSquare, AlertCircle, Beaker, ArrowLeft,
} from 'lucide-react';
import Link from 'next/link';
import { cn } from '@/lib/utils';
import { scenarios, type ScenarioProject, type ScenarioStatus } from '@/lib/api';

const STATUS_STYLE: Record<string, { dot: string; label: string }> = {
  created:   { dot: 'bg-muted-foreground', label: 'created' },
  running:   { dot: 'bg-primary animate-pulse', label: 'running' },
  completed: { dot: 'bg-emerald-500', label: 'completed' },
  failed:    { dot: 'bg-destructive', label: 'failed' },
};

export default function ScenariosPage() {
  const [list, setList] = useState<ScenarioProject[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);

  const refresh = useCallback(async () => {
    setLoading(true);
    setErr(null);
    try {
      const res = await scenarios.list();
      // Backend returns either { scenarios: [...] } or a bare null when
      // empty (Go default slice-to-JSON). Guard both shapes.
      const items = Array.isArray(res?.scenarios) ? res.scenarios : [];
      setList(items);
      if (!selectedId && items.length > 0) setSelectedId(items[0]!.id);
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Failed to load scenarios');
    } finally {
      setLoading(false);
    }
  }, [selectedId]);

  useEffect(() => { refresh(); }, []); // eslint-disable-line

  const selected = useMemo(
    () => list.find((s) => s.id === selectedId) ?? null,
    [list, selectedId],
  );

  // Poll the selected scenario if it's running — surfaces rounds as
  // they're generated by the async worker.
  useEffect(() => {
    if (!selected || selected.status !== 'running') return;
    let cancelled = false;
    const tick = async () => {
      try {
        const next = await scenarios.get(selected.id);
        if (cancelled) return;
        setList((prev) => prev.map((s) => (s.id === next.id ? next : s)));
        if (next.status === 'running') setTimeout(tick, 2000);
      } catch {
        // polling failure is non-fatal; user can refresh manually
      }
    };
    const t = setTimeout(tick, 2000);
    return () => { cancelled = true; clearTimeout(t); };
  }, [selected]);

  const runIt = async (s: ScenarioProject) => {
    try {
      await scenarios.run(s.id);
      refresh();
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Failed to start');
    }
  };

  return (
    <div className="flex h-full min-h-0 flex-col gap-3 full-bleed p-4 lg:p-6">
      {/* Labs provenance banner */}
      <div className="flex items-center gap-2 rounded-md border border-amber-500/30 bg-amber-500/5 px-3 py-1.5 text-2xs text-amber-600">
        <Beaker className="h-3.5 w-3.5 shrink-0" />
        <span>Experimental — this is a Labs feature. Results don&apos;t affect your real data.</span>
        <Link href="/labs" className="ml-auto flex items-center gap-1 hover:underline">
          <ArrowLeft className="h-3 w-3" /> Labs
        </Link>
      </div>

      <header className="flex items-center gap-3">
        <FlaskConical className="h-6 w-6 text-primary" />
        <div>
          <h1 className="text-lg font-semibold">Scenario Lab</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Multi-agent simulations — seed a premise, watch the team play it out. Not a production path.
          </p>
        </div>
        <button
          onClick={refresh}
          disabled={loading}
          className="ml-auto inline-flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:bg-accent"
        >
          {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
          Refresh
        </button>
      </header>

      {err && (
        <div className="flex items-center gap-2 rounded-lg border border-destructive/40 bg-destructive/5 p-3 text-xs text-destructive">
          <AlertCircle className="h-4 w-4" />
          <span>{err}</span>
        </div>
      )}

      <div className="grid min-h-0 flex-1 grid-cols-1 gap-3 lg:grid-cols-[300px_1fr]">
        {/* Rail */}
        <aside className="flex min-h-0 flex-col gap-2 overflow-hidden">
          <button
            onClick={() => setCreating((v) => !v)}
            className="flex items-center gap-2 rounded-md border border-dashed border-border px-3 py-1.5 text-xs text-muted-foreground hover:border-primary/40 hover:text-foreground"
          >
            <Plus className="h-3.5 w-3.5" />
            {creating ? 'Cancel new scenario' : 'New scenario'}
          </button>
          {creating && <CreateForm onCreated={(c) => { setCreating(false); setList((p) => [c, ...p]); setSelectedId(c.id); }} />}
          <div className="flex-1 overflow-y-auto rounded-xl border border-border bg-card/40">
            {list.length === 0 ? (
              <p className="p-3 text-2xs text-muted-foreground">
                No scenarios yet. Create one above to seed a multi-agent simulation.
              </p>
            ) : (
              <ul className="divide-y divide-border/60">
                {list.map((s) => {
                  const ss = STATUS_STYLE[s.status] ?? STATUS_STYLE.created!;
                  return (
                    <li key={s.id}>
                      <button
                        onClick={() => setSelectedId(s.id)}
                        className={cn(
                          'flex w-full flex-col gap-1 px-3 py-2 text-left text-2xs transition-colors hover:bg-accent/40',
                          selectedId === s.id && 'bg-primary/5',
                        )}
                      >
                        <div className="flex items-center gap-2">
                          <span className={cn('h-2 w-2 rounded-full', ss.dot)} />
                          <span className="font-mono lowercase text-muted-foreground">{ss.label}</span>
                          <span className="ml-auto text-muted-foreground">
                            {s.agent_count} agents · {s.rounds} rounds
                          </span>
                        </div>
                        <p className="line-clamp-2 font-medium text-foreground">
                          {s.name || s.seed.slice(0, 60) || '(unnamed)'}
                        </p>
                        <div className="flex items-center gap-1 text-muted-foreground/60">
                          <Clock className="h-3 w-3" />
                          {new Date(s.created_at).toLocaleString()}
                        </div>
                      </button>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>
        </aside>

        {/* Detail */}
        <section className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-border bg-card/40">
          {!selected ? (
            <div className="flex flex-1 items-center justify-center p-6 text-center">
              <p className="text-sm text-muted-foreground">
                Pick a scenario, or create a new one.
              </p>
            </div>
          ) : (
            <ScenarioDetail scenario={selected} onRun={() => runIt(selected)} />
          )}
        </section>
      </div>
    </div>
  );
}

function CreateForm({ onCreated }: { onCreated: (s: ScenarioProject) => void }) {
  const [name, setName] = useState('');
  const [seed, setSeed] = useState('');
  const [agentCount, setAgentCount] = useState(5);
  const [rounds, setRounds] = useState(5);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!seed.trim()) return;
    setBusy(true);
    setErr(null);
    try {
      const s = await scenarios.create({
        name: name.trim() || undefined,
        seed: seed.trim(),
        agent_count: agentCount,
        rounds,
      });
      onCreated(s);
    } catch (e) {
      setErr(e instanceof Error ? e.message : 'Create failed');
    } finally {
      setBusy(false);
    }
  };

  return (
    <form onSubmit={submit} className="space-y-2 rounded-xl border border-border bg-card p-3 text-xs">
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Name (optional)"
        className="qr-input text-xs"
      />
      <textarea
        value={seed}
        onChange={(e) => setSeed(e.target.value)}
        placeholder="Seed premise — e.g. &quot;A startup's founders debate whether to pivot after missing Q1&quot;"
        rows={3}
        required
        className="qr-textarea text-xs"
      />
      <div className="grid grid-cols-2 gap-2">
        <label className="flex flex-col gap-0.5 text-2xs text-muted-foreground">
          Agents
          <input
            type="number" min={2} max={12}
            value={agentCount}
            onChange={(e) => setAgentCount(Number(e.target.value))}
            className="qr-input text-xs"
          />
        </label>
        <label className="flex flex-col gap-0.5 text-2xs text-muted-foreground">
          Rounds
          <input
            type="number" min={1} max={20}
            value={rounds}
            onChange={(e) => setRounds(Number(e.target.value))}
            className="qr-input text-xs"
          />
        </label>
      </div>
      <button
        type="submit"
        disabled={busy || !seed.trim()}
        className="inline-flex w-full items-center justify-center gap-1.5 rounded-md bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
      >
        {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Plus className="h-3.5 w-3.5" />}
        Create
      </button>
      {err && <p className="text-2xs text-destructive">{err}</p>}
    </form>
  );
}

function ScenarioDetail({ scenario, onRun }: { scenario: ScenarioProject; onRun: () => void }) {
  const ss = STATUS_STYLE[scenario.status] ?? STATUS_STYLE.created!;
  const canRun = scenario.status === 'created' || scenario.status === 'failed';
  return (
    <>
      <header className="space-y-2 border-b border-border/60 p-4">
        <div className="flex items-center gap-2">
          <span className={cn('h-2 w-2 rounded-full', ss.dot)} />
          <span className="font-mono text-2xs lowercase text-muted-foreground">{ss.label}</span>
          <span className="ml-auto flex items-center gap-2 font-mono text-2xs text-muted-foreground">
            {scenario.agent_count} agents · {scenario.rounds} rounds
          </span>
        </div>
        <h3 className="text-base font-semibold">{scenario.name || '(unnamed)'}</h3>
        <p className="text-xs text-muted-foreground">{scenario.seed}</p>
        {canRun && (
          <button
            onClick={onRun}
            className="mt-1 inline-flex items-center gap-1.5 rounded-md bg-primary px-3 py-1 text-xs font-medium text-primary-foreground hover:bg-primary/90"
          >
            <Play className="h-3.5 w-3.5" />
            Run
          </button>
        )}
      </header>

      <div className="flex-1 overflow-y-auto p-4">
        {scenario.agents && scenario.agents.length > 0 && (
          <section className="mb-4">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Cast
            </h3>
            <div className="grid gap-2 md:grid-cols-2">
              {scenario.agents.map((a) => (
                <div key={a.id} className="rounded-lg border border-border bg-card p-3 text-xs">
                  <div className="flex items-center gap-2 font-semibold">
                    {a.name}
                    <span className="rounded-sm bg-primary/10 px-1.5 py-0.5 text-xs font-mono text-primary">
                      {a.role}
                    </span>
                  </div>
                  <p className="mt-1 text-muted-foreground">{a.bio}</p>
                  {a.stance && <p className="mt-1 italic text-muted-foreground/80">{a.stance}</p>}
                </div>
              ))}
            </div>
          </section>
        )}

        {scenario.rounds_data && scenario.rounds_data.length > 0 && (
          <section className="mb-4">
            <h3 className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              <MessageSquare className="h-3 w-3" />
              Rounds ({scenario.rounds_data.length})
            </h3>
            <ol className="space-y-2">
              {scenario.rounds_data.map((r) => (
                <li key={`${r.number}-${r.agent_id}-${r.timestamp}`} className="rounded-lg border border-border bg-card p-3 text-xs">
                  <div className="flex items-center gap-2 text-2xs">
                    <span className="rounded-sm bg-muted px-1.5 py-0.5 font-mono text-muted-foreground">
                      R{r.number}
                    </span>
                    <span className="font-semibold">{r.agent_name}</span>
                    <span className="ml-auto text-muted-foreground">
                      {new Date(r.timestamp).toLocaleTimeString()}
                    </span>
                  </div>
                  <p className="mt-1 whitespace-pre-wrap leading-relaxed">{r.content}</p>
                </li>
              ))}
            </ol>
          </section>
        )}

        {scenario.report && (
          <section className="rounded-xl border border-primary/30 bg-primary/5 p-4">
            <h3 className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-primary">
              <CheckCircle2 className="h-3.5 w-3.5" />
              Report
            </h3>
            <p className="whitespace-pre-wrap text-sm leading-relaxed">{scenario.report}</p>
          </section>
        )}

        {scenario.status === 'running' && (!scenario.rounds_data || scenario.rounds_data.length === 0) && (
          <p className="text-center text-2xs text-muted-foreground">
            Agents are spinning up… this takes a few seconds for the first round.
          </p>
        )}
      </div>
    </>
  );
}
