// Copyright 2026 Qorven AI. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0 (ELv2)
// that can be found in the LICENSE file.

package connectors

import (
	"context"
	"encoding/json"
	"log/slog"
)

func j(s string) json.RawMessage { return json.RawMessage(s) }

// SeedPlatforms populates the connector knowledge base with top 20 platforms.
func SeedPlatforms(ctx context.Context, ks *KnowledgeStore) {
	platforms := []Platform{
		{ID: "gmail", Name: "Gmail", Category: "email", Description: "Send, read, and search emails via Gmail API", Icon: "mail", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://gmail.googleapis.com", DocsURL: "https://developers.google.com/gmail/api", Enabled: true},
		{ID: "google-sheets", Name: "Google Sheets", Category: "productivity", Description: "Read and write Google Sheets spreadsheets", Icon: "table", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://sheets.googleapis.com", DocsURL: "https://developers.google.com/sheets/api", Enabled: true},
		{ID: "google-drive", Name: "Google Drive", Category: "storage", Description: "Upload, download, and manage files in Google Drive", Icon: "hard-drive", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://www.googleapis.com", DocsURL: "https://developers.google.com/drive/api", Enabled: true},
		{ID: "google-calendar", Name: "Google Calendar", Category: "productivity", Description: "Create, list, and manage calendar events", Icon: "calendar", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://www.googleapis.com", DocsURL: "https://developers.google.com/calendar/api", Enabled: true},
		{ID: "slack", Name: "Slack", Category: "messaging", Description: "Send messages and manage Slack channels", Icon: "message-square", AuthType: "oauth2", AuthConfig: j(`{"provider":"slack"}`), BaseURL: "https://slack.com/api", DocsURL: "https://api.slack.com/methods", Enabled: true},
		{ID: "telegram", Name: "Telegram", Category: "messaging", Description: "Send messages, photos, and documents via Telegram Bot API", Icon: "send", AuthType: "api_key", AuthConfig: j(`{"header_name":"","prefix":""}`), BaseURL: "https://api.telegram.org", DocsURL: "https://core.telegram.org/bots/api", Enabled: true},
		{ID: "discord", Name: "Discord", Category: "messaging", Description: "Send messages and manage Discord channels", Icon: "message-circle", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://discord.com/api/v10", DocsURL: "https://discord.com/developers/docs", Enabled: true},
		{ID: "hubspot", Name: "HubSpot", Category: "crm", Description: "Manage contacts, deals, and companies in HubSpot CRM", Icon: "users", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.hubapi.com", DocsURL: "https://developers.hubspot.com/docs/api", Enabled: true},
		{ID: "notion", Name: "Notion", Category: "productivity", Description: "Create pages, search, and manage Notion databases", Icon: "file-text", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.notion.com", DocsURL: "https://developers.notion.com", Enabled: true},
		{ID: "airtable", Name: "Airtable", Category: "productivity", Description: "Read and write Airtable base records", Icon: "grid", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.airtable.com", DocsURL: "https://airtable.com/developers/web/api", Enabled: true},
		{ID: "github", Name: "GitHub", Category: "development", Description: "Manage issues, pull requests, and repositories", Icon: "git-branch", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.github.com", DocsURL: "https://docs.github.com/en/rest", Enabled: true},
		{ID: "jira", Name: "Jira", Category: "development", Description: "Create and manage Jira issues and projects", Icon: "clipboard", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://{domain}.atlassian.net", DocsURL: "https://developer.atlassian.com/cloud/jira/platform/rest/v3", Enabled: true},
		{ID: "shopify", Name: "Shopify", Category: "ecommerce", Description: "Manage products, orders, and customers in Shopify", Icon: "shopping-bag", AuthType: "api_key", AuthConfig: j(`{"header_name":"X-Shopify-Access-Token","prefix":""}`), BaseURL: "https://{shop}.myshopify.com", DocsURL: "https://shopify.dev/docs/api/admin-rest", Enabled: true},
		{ID: "stripe", Name: "Stripe", Category: "payments", Description: "Manage payments, invoices, and customers in Stripe", Icon: "credit-card", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.stripe.com", DocsURL: "https://stripe.com/docs/api", Enabled: true},
		{ID: "twitter", Name: "Twitter / X", Category: "social", Description: "Post tweets and search Twitter/X", Icon: "at-sign", AuthType: "oauth2", AuthConfig: j(`{"provider":"twitter"}`), BaseURL: "https://api.twitter.com", DocsURL: "https://developer.twitter.com/en/docs", Enabled: true},
		{ID: "linkedin", Name: "LinkedIn", Category: "social", Description: "Create posts and manage LinkedIn presence", Icon: "linkedin", AuthType: "oauth2", AuthConfig: j(`{"provider":"linkedin"}`), BaseURL: "https://api.linkedin.com", DocsURL: "https://learn.microsoft.com/en-us/linkedin/", Enabled: true},
		{ID: "wordpress", Name: "WordPress", Category: "content", Description: "Create and manage WordPress posts and pages", Icon: "globe", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://{site}/wp-json/wp/v2", DocsURL: "https://developer.wordpress.org/rest-api/", Enabled: true},
		{ID: "salesforce", Name: "Salesforce", Category: "crm", Description: "Manage leads, contacts, and opportunities in Salesforce", Icon: "cloud", AuthType: "oauth2", AuthConfig: j(`{"provider":"salesforce"}`), BaseURL: "https://{instance}.salesforce.com/services/data/v59.0", DocsURL: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta", Enabled: true},
		{ID: "trello", Name: "Trello", Category: "productivity", Description: "Manage boards, lists, and cards in Trello", Icon: "layout", AuthType: "api_key", AuthConfig: j(`{"header_name":"","prefix":""}`), BaseURL: "https://api.trello.com/1", DocsURL: "https://developer.atlassian.com/cloud/trello/rest/", Enabled: true},
		{ID: "whatsapp", Name: "WhatsApp Business", Category: "messaging", Description: "Send messages via WhatsApp Business Cloud API", Icon: "phone", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://graph.facebook.com/v18.0", DocsURL: "https://developers.facebook.com/docs/whatsapp/cloud-api", Enabled: true},
	}

	actions := []ActionDef{
		// Gmail
		{PlatformID: "gmail", ActionKey: "send_email", Name: "Send Email", Description: "Send an email via Gmail", WhenToUse: "When user asks to send an email, compose a message, write to someone, or contact someone via email", Method: "POST", Path: "/gmail/v1/users/me/messages/send", Params: j(`{"to":{"type":"string","required":true,"desc":"Recipient email address"},"subject":{"type":"string","required":true,"desc":"Email subject line"},"body":{"type":"string","required":true,"desc":"Email body (plain text or HTML)"},"cc":{"type":"string","required":false,"desc":"CC recipients, comma-separated"}}`), ResponseDesc: "Message ID and thread ID", PipedreamActionID: "gmail-send-email"},
		{PlatformID: "gmail", ActionKey: "list_messages", Name: "List Messages", Description: "List recent emails from inbox", WhenToUse: "When user asks to check email, read inbox, see new messages, or check for mail", Method: "GET", Path: "/gmail/v1/users/me/messages", Params: j(`{"maxResults":{"type":"number","required":false,"desc":"Max emails to return, default 10"},"q":{"type":"string","required":false,"desc":"Gmail search query (from:, subject:, has:attachment, etc.)"}}`), ResponseDesc: "Array of message IDs", PipedreamActionID: "gmail-list-messages"},
		{PlatformID: "gmail", ActionKey: "search_email", Name: "Search Email", Description: "Search emails by query", WhenToUse: "When user asks to find a specific email, search for messages, or look up correspondence", Method: "GET", Path: "/gmail/v1/users/me/messages", Params: j(`{"q":{"type":"string","required":true,"desc":"Gmail search query"},"maxResults":{"type":"number","required":false,"desc":"Max results, default 20"}}`), ResponseDesc: "Array of matching message IDs", PipedreamActionID: "gmail-search-messages"},

		// Google Sheets
		{PlatformID: "google-sheets", ActionKey: "read_range", Name: "Read Range", Description: "Read data from a Google Sheet range", WhenToUse: "When user asks to read a spreadsheet, get data from sheets, check a sheet, or pull data", Method: "GET", Path: "/v4/spreadsheets/{spreadsheet_id}/values/{range}", Params: j(`{"spreadsheet_id":{"type":"string","required":true,"desc":"Google Sheet ID"},"range":{"type":"string","required":true,"desc":"Cell range like Sheet1!A1:D10"}}`), ResponseDesc: "2D array of cell values"},
		{PlatformID: "google-sheets", ActionKey: "append_row", Name: "Append Row", Description: "Append a row to a Google Sheet", WhenToUse: "When user asks to add data to a spreadsheet, log something to sheets, or append a row", Method: "POST", Path: "/v4/spreadsheets/{spreadsheet_id}/values/{range}:append?valueInputOption=USER_ENTERED", Params: j(`{"spreadsheet_id":{"type":"string","required":true,"desc":"Google Sheet ID"},"range":{"type":"string","required":true,"desc":"Sheet and range like Sheet1!A:Z"},"values":{"type":"array","required":true,"desc":"Array of values for the new row"}}`), ResponseDesc: "Updated range info"},
		{PlatformID: "google-sheets", ActionKey: "update_cell", Name: "Update Cells", Description: "Update cells in a Google Sheet", WhenToUse: "When user asks to update a spreadsheet, change a value in sheets, or edit cells", Method: "PUT", Path: "/v4/spreadsheets/{spreadsheet_id}/values/{range}?valueInputOption=USER_ENTERED", Params: j(`{"spreadsheet_id":{"type":"string","required":true,"desc":"Google Sheet ID"},"range":{"type":"string","required":true,"desc":"Cell range to update"},"values":{"type":"array","required":true,"desc":"2D array of new values"}}`), ResponseDesc: "Updated cell count"},

		// Google Drive
		{PlatformID: "google-drive", ActionKey: "list_files", Name: "List Files", Description: "List files in Google Drive", WhenToUse: "When user asks to see files in Drive, list documents, or browse Drive", Method: "GET", Path: "/drive/v3/files", Params: j(`{"q":{"type":"string","required":false,"desc":"Search query (name contains, mimeType, etc.)"},"pageSize":{"type":"number","required":false,"desc":"Max files, default 20"}}`), ResponseDesc: "Array of file objects with id, name, mimeType"},
		{PlatformID: "google-drive", ActionKey: "download_file", Name: "Download File", Description: "Download a file from Google Drive", WhenToUse: "When user asks to download, get, or fetch a file from Drive", Method: "GET", Path: "/drive/v3/files/{file_id}?alt=media", Params: j(`{"file_id":{"type":"string","required":true,"desc":"Google Drive file ID"}}`), ResponseDesc: "File content"},

		// Google Calendar
		{PlatformID: "google-calendar", ActionKey: "create_event", Name: "Create Event", Description: "Create a Google Calendar event", WhenToUse: "When user asks to schedule a meeting, create an event, book time, or add to calendar", Method: "POST", Path: "/calendar/v3/calendars/primary/events", Params: j(`{"summary":{"type":"string","required":true,"desc":"Event title"},"start":{"type":"string","required":true,"desc":"Start datetime ISO 8601"},"end":{"type":"string","required":true,"desc":"End datetime ISO 8601"},"description":{"type":"string","required":false,"desc":"Event description"},"attendees":{"type":"string","required":false,"desc":"Comma-separated attendee emails"},"location":{"type":"string","required":false,"desc":"Event location"}}`), ResponseDesc: "Event ID and HTML link", PipedreamActionID: "google_calendar-create-event"},
		{PlatformID: "google-calendar", ActionKey: "list_events", Name: "List Events", Description: "List upcoming calendar events", WhenToUse: "When user asks what's on the calendar, check schedule, see upcoming meetings, or asks about availability", Method: "GET", Path: "/calendar/v3/calendars/primary/events", Params: j(`{"timeMin":{"type":"string","required":false,"desc":"Start of time range (ISO 8601, defaults to now)"},"timeMax":{"type":"string","required":false,"desc":"End of time range"},"maxResults":{"type":"number","required":false,"desc":"Max events, default 10"}}`), ResponseDesc: "Array of events with summary, start, end, attendees", PipedreamActionID: "google_calendar-list-events"},

		// Slack
		{PlatformID: "slack", ActionKey: "send_message", Name: "Send Message", Description: "Post a message to a Slack channel", WhenToUse: "When user asks to post to Slack, notify a team, send a Slack message, or message a channel", Method: "POST", Path: "/chat.postMessage", Params: j(`{"channel":{"type":"string","required":true,"desc":"Channel name or ID"},"text":{"type":"string","required":true,"desc":"Message text (supports Slack markdown)"},"thread_ts":{"type":"string","required":false,"desc":"Thread timestamp to reply to"}}`), ResponseDesc: "Message timestamp and channel"},
		{PlatformID: "slack", ActionKey: "list_channels", Name: "List Channels", Description: "List Slack channels", WhenToUse: "When user asks what Slack channels exist or wants to find a channel", Method: "GET", Path: "/conversations.list", Params: j(`{"limit":{"type":"number","required":false,"desc":"Max channels, default 100"}}`), ResponseDesc: "Array of channels with name, id, topic"},

		// Telegram
		{PlatformID: "telegram", ActionKey: "send_message", Name: "Send Message", Description: "Send a Telegram message", WhenToUse: "When user asks to send a Telegram message or notify someone on Telegram", Method: "POST", Path: "/bot{api_key}/sendMessage", Params: j(`{"chat_id":{"type":"string","required":true,"desc":"Telegram chat ID"},"text":{"type":"string","required":true,"desc":"Message text"},"parse_mode":{"type":"string","required":false,"desc":"HTML or MarkdownV2"}}`), ResponseDesc: "Message object with message_id"},

		// Discord
		{PlatformID: "discord", ActionKey: "send_message", Name: "Send Message", Description: "Send a message to a Discord channel", WhenToUse: "When user asks to send a Discord message or post in a Discord channel", Method: "POST", Path: "/channels/{channel_id}/messages", Params: j(`{"channel_id":{"type":"string","required":true,"desc":"Discord channel ID"},"content":{"type":"string","required":true,"desc":"Message content"}}`), ResponseDesc: "Message object"},

		// HubSpot
		{PlatformID: "hubspot", ActionKey: "create_contact", Name: "Create Contact", Description: "Create a contact in HubSpot CRM", WhenToUse: "When user asks to add a contact, create a lead, save someone's info to CRM, or log a new prospect", Method: "POST", Path: "/crm/v3/objects/contacts", Params: j(`{"email":{"type":"string","required":true,"desc":"Contact email"},"firstname":{"type":"string","required":false,"desc":"First name"},"lastname":{"type":"string","required":false,"desc":"Last name"},"company":{"type":"string","required":false,"desc":"Company name"},"phone":{"type":"string","required":false,"desc":"Phone number"}}`), ResponseDesc: "Contact ID and properties"},
		{PlatformID: "hubspot", ActionKey: "search_contacts", Name: "Search Contacts", Description: "Search HubSpot contacts", WhenToUse: "When user asks to find a contact, look up someone in CRM, or check if a lead exists", Method: "POST", Path: "/crm/v3/objects/contacts/search", Params: j(`{"query":{"type":"string","required":true,"desc":"Search term — name, email, or company"}}`), ResponseDesc: "Array of matching contacts"},
		{PlatformID: "hubspot", ActionKey: "list_deals", Name: "List Deals", Description: "List deals from HubSpot pipeline", WhenToUse: "When user asks about deals, pipeline status, sales progress, or revenue", Method: "GET", Path: "/crm/v3/objects/deals", Params: j(`{"limit":{"type":"number","required":false,"desc":"Max deals, default 20"}}`), ResponseDesc: "Array of deals with name, amount, stage"},

		// Notion
		{PlatformID: "notion", ActionKey: "create_page", Name: "Create Page", Description: "Create a page in Notion", WhenToUse: "When user asks to create a note, write in Notion, add a page, or document something", Method: "POST", Path: "/v1/pages", Headers: j(`{"Notion-Version":"2022-06-28"}`), Params: j(`{"title":{"type":"string","required":true,"desc":"Page title"},"content":{"type":"string","required":false,"desc":"Page content"},"parent_id":{"type":"string","required":true,"desc":"Parent page or database ID"}}`), ResponseDesc: "Page ID and URL"},
		{PlatformID: "notion", ActionKey: "search", Name: "Search", Description: "Search Notion pages and databases", WhenToUse: "When user asks to find something in Notion, search notes, or look up a document", Method: "POST", Path: "/v1/search", Headers: j(`{"Notion-Version":"2022-06-28"}`), Params: j(`{"query":{"type":"string","required":true,"desc":"Search term"}}`), ResponseDesc: "Array of matching pages"},

		// Airtable
		{PlatformID: "airtable", ActionKey: "list_records", Name: "List Records", Description: "List records from an Airtable base", WhenToUse: "When user asks to read Airtable data, check a base, or get records", Method: "GET", Path: "/v0/{base_id}/{table_name}", Params: j(`{"base_id":{"type":"string","required":true,"desc":"Airtable base ID"},"table_name":{"type":"string","required":true,"desc":"Table name"},"maxRecords":{"type":"number","required":false,"desc":"Max records, default 20"}}`), ResponseDesc: "Array of records with fields"},
		{PlatformID: "airtable", ActionKey: "create_record", Name: "Create Record", Description: "Create a record in Airtable", WhenToUse: "When user asks to add to Airtable, create a record, or log data", Method: "POST", Path: "/v0/{base_id}/{table_name}", Params: j(`{"base_id":{"type":"string","required":true,"desc":"Airtable base ID"},"table_name":{"type":"string","required":true,"desc":"Table name"},"fields":{"type":"object","required":true,"desc":"Field values as key-value pairs"}}`), ResponseDesc: "Created record ID"},

		// GitHub
		{PlatformID: "github", ActionKey: "create_issue", Name: "Create Issue", Description: "Create a GitHub issue", WhenToUse: "When user asks to create a bug report, file an issue, or create a ticket on GitHub", Method: "POST", Path: "/repos/{owner}/{repo}/issues", Params: j(`{"owner":{"type":"string","required":true,"desc":"Repository owner"},"repo":{"type":"string","required":true,"desc":"Repository name"},"title":{"type":"string","required":true,"desc":"Issue title"},"body":{"type":"string","required":false,"desc":"Issue description"},"labels":{"type":"array","required":false,"desc":"Label names"}}`), ResponseDesc: "Issue number and URL"},
		{PlatformID: "github", ActionKey: "list_prs", Name: "List Pull Requests", Description: "List open pull requests", WhenToUse: "When user asks about PRs, open pull requests, or what needs review", Method: "GET", Path: "/repos/{owner}/{repo}/pulls", Params: j(`{"owner":{"type":"string","required":true,"desc":"Repository owner"},"repo":{"type":"string","required":true,"desc":"Repository name"},"state":{"type":"string","required":false,"desc":"open, closed, or all"}}`), ResponseDesc: "Array of PRs with title, author, number"},

		// Jira
		{PlatformID: "jira", ActionKey: "create_issue", Name: "Create Issue", Description: "Create a Jira issue", WhenToUse: "When user asks to create a Jira ticket, file a bug, or add a task in Jira", Method: "POST", Path: "/rest/api/3/issue", Params: j(`{"project_key":{"type":"string","required":true,"desc":"Project key (e.g. PROJ)"},"summary":{"type":"string","required":true,"desc":"Issue title"},"description":{"type":"string","required":false,"desc":"Issue description"},"issuetype":{"type":"string","required":false,"desc":"Bug, Story, Task (default Task)"}}`), ResponseDesc: "Issue key and URL"},

		// Shopify
		{PlatformID: "shopify", ActionKey: "list_orders", Name: "List Orders", Description: "List recent Shopify orders", WhenToUse: "When user asks about orders, recent sales, or store activity", Method: "GET", Path: "/admin/api/2024-01/orders.json", Params: j(`{"status":{"type":"string","required":false,"desc":"open, closed, any"},"limit":{"type":"number","required":false,"desc":"Max orders, default 20"}}`), ResponseDesc: "Array of orders with number, customer, total"},
		{PlatformID: "shopify", ActionKey: "list_products", Name: "List Products", Description: "List Shopify products", WhenToUse: "When user asks about products, inventory, or wants to check stock", Method: "GET", Path: "/admin/api/2024-01/products.json", Params: j(`{"limit":{"type":"number","required":false,"desc":"Max products, default 20"}}`), ResponseDesc: "Array of products with title, price, inventory"},

		// Stripe
		{PlatformID: "stripe", ActionKey: "list_payments", Name: "List Payments", Description: "List recent Stripe payments", WhenToUse: "When user asks about payments, transactions, revenue, or payment history", Method: "GET", Path: "/v1/payment_intents", Params: j(`{"limit":{"type":"number","required":false,"desc":"Max payments, default 20"}}`), ResponseDesc: "Array of payments with amount, status, customer"},
		{PlatformID: "stripe", ActionKey: "create_invoice", Name: "Create Invoice", Description: "Create a Stripe invoice", WhenToUse: "When user asks to invoice someone, create a bill, or charge a customer", Method: "POST", Path: "/v1/invoices", Params: j(`{"customer":{"type":"string","required":true,"desc":"Stripe customer ID"},"description":{"type":"string","required":false,"desc":"Invoice description"}}`), ResponseDesc: "Invoice ID and URL"},

		// Twitter/X
		{PlatformID: "twitter", ActionKey: "post_tweet", Name: "Post Tweet", Description: "Post a tweet on Twitter/X", WhenToUse: "When user asks to tweet, post on Twitter/X, or share on social media", Method: "POST", Path: "/2/tweets", Params: j(`{"text":{"type":"string","required":true,"desc":"Tweet text, max 280 chars"}}`), ResponseDesc: "Tweet ID", ExecutionBackend: "pipedream", PipedreamActionID: "twitter-create-tweet"},
		{PlatformID: "twitter", ActionKey: "search_tweets", Name: "Search Tweets", Description: "Search recent tweets", WhenToUse: "When user asks to search Twitter, find tweets, or see what people are saying", Method: "GET", Path: "/2/tweets/search/recent", Params: j(`{"query":{"type":"string","required":true,"desc":"Search query"},"max_results":{"type":"number","required":false,"desc":"Max tweets, 10-100"}}`), ResponseDesc: "Array of tweets", ExecutionBackend: "pipedream", PipedreamActionID: "twitter-search-tweets"},

		// LinkedIn
		{PlatformID: "linkedin", ActionKey: "create_post", Name: "Create Post", Description: "Create a LinkedIn post", WhenToUse: "When user asks to post on LinkedIn, share an update, or publish on LinkedIn", Method: "POST", Path: "/v2/ugcPosts", Params: j(`{"text":{"type":"string","required":true,"desc":"Post text content"}}`), ResponseDesc: "Post ID", ExecutionBackend: "pipedream", PipedreamActionID: "linkedin-create-share"},

		// WordPress
		{PlatformID: "wordpress", ActionKey: "create_post", Name: "Create Post", Description: "Create a WordPress blog post", WhenToUse: "When user asks to create a blog post, publish an article, or write on WordPress", Method: "POST", Path: "/posts", Params: j(`{"title":{"type":"string","required":true,"desc":"Post title"},"content":{"type":"string","required":true,"desc":"Post content (HTML)"},"status":{"type":"string","required":false,"desc":"draft or publish, default draft"}}`), ResponseDesc: "Post ID and URL"},

		// Salesforce
		{PlatformID: "salesforce", ActionKey: "create_lead", Name: "Create Lead", Description: "Create a lead in Salesforce", WhenToUse: "When user asks to add a lead to Salesforce or save a prospect", Method: "POST", Path: "/sobjects/Lead", Params: j(`{"FirstName":{"type":"string","required":false,"desc":"First name"},"LastName":{"type":"string","required":true,"desc":"Last name"},"Email":{"type":"string","required":false,"desc":"Email"},"Company":{"type":"string","required":true,"desc":"Company name"}}`), ResponseDesc: "Lead ID"},
		{PlatformID: "salesforce", ActionKey: "search", Name: "Search Records", Description: "Search Salesforce records using SOSL", WhenToUse: "When user asks to find something in Salesforce, search CRM, or look up a record", Method: "GET", Path: "/search/?q=FIND+{query}+IN+ALL+FIELDS", Params: j(`{"query":{"type":"string","required":true,"desc":"Search term"}}`), ResponseDesc: "Array of matching records"},

		// Trello
		{PlatformID: "trello", ActionKey: "create_card", Name: "Create Card", Description: "Create a Trello card", WhenToUse: "When user asks to create a Trello card, add a task to a board, or create a to-do", Method: "POST", Path: "/cards", Params: j(`{"name":{"type":"string","required":true,"desc":"Card title"},"idList":{"type":"string","required":true,"desc":"List ID to add card to"},"desc":{"type":"string","required":false,"desc":"Card description"}}`), ResponseDesc: "Card ID and URL"},

		// WhatsApp
		{PlatformID: "whatsapp", ActionKey: "send_message", Name: "Send Message", Description: "Send a WhatsApp message", WhenToUse: "When user asks to send a WhatsApp message or text someone on WhatsApp", Method: "POST", Path: "/{phone_number_id}/messages", Params: j(`{"phone_number_id":{"type":"string","required":true,"desc":"WhatsApp phone number ID"},"to":{"type":"string","required":true,"desc":"Recipient phone with country code"},"text":{"type":"string","required":true,"desc":"Message text"}}`), ResponseDesc: "Message ID"},
	}

	for _, p := range platforms {
		if err := ks.UpsertPlatform(ctx, p); err != nil {
			slog.Warn("seed.platform_failed", "id", p.ID, "error", err)
		}
	}
	for _, a := range actions {
		if err := ks.UpsertAction(ctx, a); err != nil {
			slog.Warn("seed.action_failed", "platform", a.PlatformID, "action", a.ActionKey, "error", err)
		}
	}
	slog.Info("seed.complete", "platforms", len(platforms), "actions", len(actions))
}

// SeedExpandedPlatforms adds 30+ additional platforms beyond the core 20.
func SeedExpandedPlatforms(ctx context.Context, ks *KnowledgeStore) {
	platforms := []Platform{
		// Social platforms (Pipedream-only)
		{ID: "facebook", Name: "Facebook Pages", Category: "social", Description: "Post to and manage Facebook Pages", Icon: "thumbs-up", AuthType: "oauth2", AuthConfig: j(`{"provider":"facebook"}`), BaseURL: "https://graph.facebook.com/v18.0", DocsURL: "https://developers.facebook.com/docs/pages-api", Enabled: true},
		{ID: "instagram", Name: "Instagram Business", Category: "social", Description: "Post photos and reels to Instagram", Icon: "camera", AuthType: "oauth2", AuthConfig: j(`{"provider":"instagram"}`), BaseURL: "https://graph.facebook.com/v18.0", DocsURL: "https://developers.facebook.com/docs/instagram-api", Enabled: true},
		{ID: "tiktok", Name: "TikTok", Category: "social", Description: "Upload videos to TikTok", Icon: "music", AuthType: "oauth2", AuthConfig: j(`{"provider":"tiktok"}`), BaseURL: "https://open.tiktokapis.com/v2", DocsURL: "https://developers.tiktok.com/doc/", Enabled: true},
		{ID: "youtube", Name: "YouTube", Category: "social", Description: "Upload videos and manage YouTube channel", Icon: "play-circle", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://www.googleapis.com/youtube/v3", DocsURL: "https://developers.google.com/youtube/v3", Enabled: true},
		{ID: "threads", Name: "Threads", Category: "social", Description: "Post to Threads", Icon: "at-sign", AuthType: "oauth2", AuthConfig: j(`{"provider":"threads"}`), BaseURL: "https://graph.threads.net/v1.0", DocsURL: "https://developers.facebook.com/docs/threads", Enabled: true},
		{ID: "bluesky", Name: "Bluesky", Category: "social", Description: "Post to Bluesky", Icon: "cloud", AuthType: "oauth2", AuthConfig: j(`{"provider":"bluesky"}`), BaseURL: "https://bsky.social/xrpc", DocsURL: "https://docs.bsky.app/", Enabled: true},
		{ID: "pinterest", Name: "Pinterest", Category: "social", Description: "Create pins on Pinterest", Icon: "image", AuthType: "oauth2", AuthConfig: j(`{"provider":"pinterest"}`), BaseURL: "https://api.pinterest.com/v5", DocsURL: "https://developers.pinterest.com/docs/api/v5/", Enabled: true},
		{ID: "mastodon", Name: "Mastodon", Category: "social", Description: "Post to Mastodon", Icon: "globe", AuthType: "oauth2", AuthConfig: j(`{"provider":"mastodon"}`), BaseURL: "https://{instance}/api/v1", DocsURL: "https://docs.joinmastodon.org/api/", Enabled: true},
		{ID: "reddit", Name: "Reddit", Category: "social", Description: "Submit posts to Reddit", Icon: "message-circle", AuthType: "oauth2", AuthConfig: j(`{"provider":"reddit"}`), BaseURL: "https://oauth.reddit.com/api", DocsURL: "https://www.reddit.com/dev/api/", Enabled: true},
		{ID: "microsoft-outlook", Name: "Microsoft Outlook", Category: "email", Description: "Send and read emails via Microsoft Graph API", Icon: "mail", AuthType: "oauth2", AuthConfig: j(`{"provider":"microsoft"}`), BaseURL: "https://graph.microsoft.com/v1.0", DocsURL: "https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview", Enabled: true},
		{ID: "microsoft-teams", Name: "Microsoft Teams", Category: "messaging", Description: "Send messages and manage Teams channels", Icon: "message-square", AuthType: "oauth2", AuthConfig: j(`{"provider":"microsoft"}`), BaseURL: "https://graph.microsoft.com/v1.0", DocsURL: "https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview", Enabled: true},
		{ID: "microsoft-onedrive", Name: "Microsoft OneDrive", Category: "storage", Description: "Upload, download, and manage OneDrive files", Icon: "cloud", AuthType: "oauth2", AuthConfig: j(`{"provider":"microsoft"}`), BaseURL: "https://graph.microsoft.com/v1.0", DocsURL: "https://learn.microsoft.com/en-us/graph/api/resources/onedrive", Enabled: true},
		{ID: "microsoft-excel", Name: "Microsoft Excel Online", Category: "productivity", Description: "Read and write Excel workbooks via Graph API", Icon: "table", AuthType: "oauth2", AuthConfig: j(`{"provider":"microsoft"}`), BaseURL: "https://graph.microsoft.com/v1.0", DocsURL: "https://learn.microsoft.com/en-us/graph/api/resources/excel", Enabled: true},
		{ID: "zoom", Name: "Zoom", Category: "communication", Description: "Create and manage Zoom meetings", Icon: "video", AuthType: "oauth2", AuthConfig: j(`{"auth_url":"https://zoom.us/oauth/authorize","token_url":"https://zoom.us/oauth/token"}`), BaseURL: "https://api.zoom.us/v2", DocsURL: "https://developers.zoom.us/docs/api/", Enabled: true},
		{ID: "asana", Name: "Asana", Category: "productivity", Description: "Manage tasks, projects, and teams in Asana", Icon: "check-square", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://app.asana.com/api/1.0", DocsURL: "https://developers.asana.com/docs", Enabled: true},
		{ID: "clickup", Name: "ClickUp", Category: "productivity", Description: "Manage tasks, spaces, and lists in ClickUp", Icon: "check-circle", AuthType: "api_key", AuthConfig: j(`{"header_name":"Authorization","prefix":""}`), BaseURL: "https://api.clickup.com/api/v2", DocsURL: "https://clickup.com/api", Enabled: true},
		{ID: "linear", Name: "Linear", Category: "development", Description: "Manage issues and projects in Linear", Icon: "zap", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.linear.app", DocsURL: "https://developers.linear.app/docs", Enabled: true},
		{ID: "todoist", Name: "Todoist", Category: "productivity", Description: "Manage tasks and projects in Todoist", Icon: "check", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.todoist.com/rest/v2", DocsURL: "https://developer.todoist.com/rest/v2/", Enabled: true},
		{ID: "zendesk", Name: "Zendesk", Category: "support", Description: "Manage support tickets and customers in Zendesk", Icon: "headphones", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://{subdomain}.zendesk.com/api/v2", DocsURL: "https://developer.zendesk.com/api-reference/", Enabled: true},
		{ID: "freshdesk", Name: "Freshdesk", Category: "support", Description: "Manage support tickets in Freshdesk", Icon: "headphones", AuthType: "api_key", AuthConfig: j(`{"header_name":"Authorization","prefix":"Basic "}`), BaseURL: "https://{domain}.freshdesk.com/api/v2", DocsURL: "https://developers.freshdesk.com/api/", Enabled: true},
		{ID: "intercom", Name: "Intercom", Category: "support", Description: "Manage conversations and contacts in Intercom", Icon: "message-circle", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.intercom.io", DocsURL: "https://developers.intercom.com/docs", Enabled: true},
		{ID: "mailchimp", Name: "Mailchimp", Category: "marketing", Description: "Manage email campaigns and audiences in Mailchimp", Icon: "mail", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://{dc}.api.mailchimp.com/3.0", DocsURL: "https://mailchimp.com/developer/marketing/api/", Enabled: true},
		{ID: "sendgrid", Name: "SendGrid", Category: "email", Description: "Send transactional and marketing emails via SendGrid", Icon: "send", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.sendgrid.com/v3", DocsURL: "https://docs.sendgrid.com/api-reference", Enabled: true},
		{ID: "twilio", Name: "Twilio", Category: "communication", Description: "Send SMS, make calls, and manage phone numbers", Icon: "phone", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://api.twilio.com/2010-04-01", DocsURL: "https://www.twilio.com/docs/usage/api", Enabled: true},
		{ID: "paypal", Name: "PayPal", Category: "payments", Description: "Manage payments and invoices via PayPal", Icon: "dollar-sign", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api-m.paypal.com/v2", DocsURL: "https://developer.paypal.com/docs/api/overview/", Enabled: true},
		{ID: "quickbooks", Name: "QuickBooks", Category: "accounting", Description: "Manage invoices, customers, and accounting in QuickBooks", Icon: "book", AuthType: "oauth2", AuthConfig: j(`{"auth_url":"https://appcenter.intuit.com/connect/oauth2","token_url":"https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"}`), BaseURL: "https://quickbooks.api.intuit.com/v3", DocsURL: "https://developer.intuit.com/app/developer/qbo/docs/api", Enabled: true},
		{ID: "xero", Name: "Xero", Category: "accounting", Description: "Manage invoices and accounting in Xero", Icon: "book-open", AuthType: "oauth2", AuthConfig: j(`{"auth_url":"https://login.xero.com/identity/connect/authorize","token_url":"https://identity.xero.com/connect/token"}`), BaseURL: "https://api.xero.com/api.xro/2.0", DocsURL: "https://developer.xero.com/documentation/api/", Enabled: true},
		{ID: "dropbox", Name: "Dropbox", Category: "storage", Description: "Upload, download, and manage Dropbox files", Icon: "box", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.dropboxapi.com/2", DocsURL: "https://www.dropbox.com/developers/documentation", Enabled: true},
		{ID: "box", Name: "Box", Category: "storage", Description: "Manage files and folders in Box", Icon: "archive", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.box.com/2.0", DocsURL: "https://developer.box.com/reference/", Enabled: true},
		{ID: "supabase", Name: "Supabase", Category: "database", Description: "Query and manage Supabase PostgreSQL databases", Icon: "database", AuthType: "api_key", AuthConfig: j(`{"header_name":"apikey","prefix":""}`), BaseURL: "https://{project}.supabase.co/rest/v1", DocsURL: "https://supabase.com/docs/guides/api", Enabled: true},
		{ID: "mongodb", Name: "MongoDB Atlas", Category: "database", Description: "Query and manage MongoDB Atlas databases", Icon: "database", AuthType: "api_key", AuthConfig: j(`{"header_name":"api-key","prefix":""}`), BaseURL: "https://data.mongodb-api.com/app/{app_id}/endpoint/data/v1", DocsURL: "https://www.mongodb.com/docs/atlas/api/", Enabled: true},
		{ID: "calendly", Name: "Calendly", Category: "productivity", Description: "Manage scheduling and events in Calendly", Icon: "calendar", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.calendly.com", DocsURL: "https://developer.calendly.com/api-docs", Enabled: true},
		{ID: "typeform", Name: "Typeform", Category: "forms", Description: "Manage forms and responses in Typeform", Icon: "file-text", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.typeform.com", DocsURL: "https://developer.typeform.com/", Enabled: true},
		{ID: "figma", Name: "Figma", Category: "design", Description: "Access Figma files, components, and comments", Icon: "pen-tool", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.figma.com/v1", DocsURL: "https://www.figma.com/developers/api", Enabled: true},
		{ID: "datadog", Name: "Datadog", Category: "monitoring", Description: "Query metrics, manage monitors and dashboards", Icon: "activity", AuthType: "api_key", AuthConfig: j(`{"header_name":"DD-API-KEY","prefix":""}`), BaseURL: "https://api.datadoghq.com/api/v1", DocsURL: "https://docs.datadoghq.com/api/", Enabled: true},
		{ID: "cloudinary", Name: "Cloudinary", Category: "media", Description: "Upload and manage images and videos", Icon: "image", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://api.cloudinary.com/v1_1/{cloud_name}", DocsURL: "https://cloudinary.com/documentation/admin_api", Enabled: true},
		{ID: "google-docs", Name: "Google Docs", Category: "productivity", Description: "Create and edit Google Docs documents", Icon: "file-text", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://docs.googleapis.com", DocsURL: "https://developers.google.com/docs/api", Enabled: true},
		{ID: "pipedrive", Name: "Pipedrive", Category: "crm", Description: "Manage deals, contacts, and activities in Pipedrive", Icon: "trending-up", AuthType: "api_key", AuthConfig: j(`{"header_name":"","prefix":""}`), BaseURL: "https://api.pipedrive.com/v1", DocsURL: "https://developers.pipedrive.com/docs/api/v1", Enabled: true},
		{ID: "zoho-crm", Name: "Zoho CRM", Category: "crm", Description: "Manage leads, contacts, and deals in Zoho CRM", Icon: "users", AuthType: "oauth2", AuthConfig: j(`{"auth_url":"https://accounts.zoho.com/oauth/v2/auth","token_url":"https://accounts.zoho.com/oauth/v2/token"}`), BaseURL: "https://www.zohoapis.com/crm/v2", DocsURL: "https://www.zoho.com/crm/developer/docs/api/v2/", Enabled: true},
		{ID: "elevenlabs", Name: "ElevenLabs", Category: "ai", Description: "Text-to-speech and voice synthesis", Icon: "mic", AuthType: "api_key", AuthConfig: j(`{"header_name":"xi-api-key","prefix":""}`), BaseURL: "https://api.elevenlabs.io/v1", DocsURL: "https://docs.elevenlabs.io/api-reference", Enabled: true},
		{ID: "resend", Name: "Resend", Category: "email", Description: "Send transactional emails via Resend", Icon: "send", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.resend.com", DocsURL: "https://resend.com/docs/api-reference", Enabled: true},
	}

	actions := []ActionDef{
		// Social platforms (Pipedream-backend)
		{PlatformID: "facebook", ActionKey: "create_post", Name: "Create Post", Description: "Post to a Facebook Page", WhenToUse: "When user asks to post on Facebook or share on their page", Method: "POST", Path: "/{page_id}/feed", Params: j(`{"message":{"type":"string","required":true,"desc":"Post content"},"link":{"type":"string","required":false,"desc":"URL to share"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "facebook_pages-create-post"},
		{PlatformID: "instagram", ActionKey: "create_photo_post", Name: "Post Photo", Description: "Post a photo to Instagram", WhenToUse: "When user asks to post a photo on Instagram", Method: "POST", Path: "/{ig_user_id}/media", Params: j(`{"image_url":{"type":"string","required":true,"desc":"Public URL of image"},"caption":{"type":"string","required":true,"desc":"Post caption"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "instagram_for_business-create-photo-post"},
		{PlatformID: "youtube", ActionKey: "upload_video", Name: "Upload Video", Description: "Upload a video to YouTube", WhenToUse: "When user asks to upload or publish a video to YouTube", Method: "POST", Path: "/videos?part=snippet,status", Params: j(`{"title":{"type":"string","required":true,"desc":"Video title"},"description":{"type":"string","required":false,"desc":"Video description"},"file_url":{"type":"string","required":true,"desc":"URL of video file"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "youtube-upload-video"},
		{PlatformID: "tiktok", ActionKey: "upload_video", Name: "Upload Video", Description: "Upload a video to TikTok", WhenToUse: "When user asks to post or upload a TikTok video", Method: "POST", Path: "/post/publish/video/init/", Params: j(`{"video_url":{"type":"string","required":true,"desc":"Public URL of video"},"caption":{"type":"string","required":true,"desc":"Video caption"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "tiktok-upload-video"},
		{PlatformID: "threads", ActionKey: "create_post", Name: "Create Post", Description: "Post to Threads", WhenToUse: "When user asks to post on Threads", Method: "POST", Path: "/{user_id}/threads", Params: j(`{"text":{"type":"string","required":true,"desc":"Post text"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "threads-create-post"},
		{PlatformID: "bluesky", ActionKey: "create_post", Name: "Create Post", Description: "Post to Bluesky", WhenToUse: "When user asks to post on Bluesky", Method: "POST", Path: "/com.atproto.repo.createRecord", Params: j(`{"text":{"type":"string","required":true,"desc":"Post text"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "bluesky-create-post"},
		{PlatformID: "pinterest", ActionKey: "create_pin", Name: "Create Pin", Description: "Create a Pinterest pin", WhenToUse: "When user asks to create a pin on Pinterest", Method: "POST", Path: "/pins", Params: j(`{"board_id":{"type":"string","required":true,"desc":"Board ID"},"image_url":{"type":"string","required":true,"desc":"Image URL"},"title":{"type":"string","required":false,"desc":"Pin title"},"description":{"type":"string","required":false,"desc":"Pin description"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "pinterest-create-pin"},
		{PlatformID: "mastodon", ActionKey: "create_status", Name: "Post Status", Description: "Post to Mastodon", WhenToUse: "When user asks to post on Mastodon or toot", Method: "POST", Path: "/statuses", Params: j(`{"status":{"type":"string","required":true,"desc":"Toot content"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "mastodon-create-status"},
		{PlatformID: "reddit", ActionKey: "submit_post", Name: "Submit Post", Description: "Submit a post to a subreddit", WhenToUse: "When user asks to post on Reddit or submit to a subreddit", Method: "POST", Path: "/submit", Params: j(`{"sr":{"type":"string","required":true,"desc":"Subreddit name"},"title":{"type":"string","required":true,"desc":"Post title"},"text":{"type":"string","required":false,"desc":"Post body text"},"url":{"type":"string","required":false,"desc":"Link URL (for link posts)"}}`), ExecutionBackend: "pipedream", PipedreamActionID: "reddit-submit-post"},
		// Microsoft Outlook
		{PlatformID: "microsoft-outlook", ActionKey: "send_email", Name: "Send Email", Description: "Send an email via Outlook", WhenToUse: "When user asks to send email via Outlook or Microsoft mail", Method: "POST", Path: "/me/sendMail", Params: j(`{"to":{"type":"string","required":true,"desc":"Recipient email"},"subject":{"type":"string","required":true,"desc":"Subject"},"body":{"type":"string","required":true,"desc":"Email body"}}`)},
		{PlatformID: "microsoft-outlook", ActionKey: "list_messages", Name: "List Messages", Description: "List recent Outlook emails", WhenToUse: "When user asks to check Outlook inbox", Method: "GET", Path: "/me/messages", Params: j(`{"$top":{"type":"number","required":false,"desc":"Max messages"}}`)},
		// Microsoft Teams
		{PlatformID: "microsoft-teams", ActionKey: "send_message", Name: "Send Message", Description: "Send a Teams channel message", WhenToUse: "When user asks to post in Microsoft Teams", Method: "POST", Path: "/teams/{team_id}/channels/{channel_id}/messages", Params: j(`{"team_id":{"type":"string","required":true,"desc":"Team ID"},"channel_id":{"type":"string","required":true,"desc":"Channel ID"},"content":{"type":"string","required":true,"desc":"Message"}}`)},
		// Zoom
		{PlatformID: "zoom", ActionKey: "create_meeting", Name: "Create Meeting", Description: "Create a Zoom meeting", WhenToUse: "When user asks to schedule a Zoom call or video meeting", Method: "POST", Path: "/users/me/meetings", Params: j(`{"topic":{"type":"string","required":true,"desc":"Meeting topic"},"start_time":{"type":"string","required":true,"desc":"Start time ISO 8601"},"duration":{"type":"number","required":false,"desc":"Duration in minutes"}}`)},
		{PlatformID: "zoom", ActionKey: "list_meetings", Name: "List Meetings", Description: "List upcoming Zoom meetings", WhenToUse: "When user asks about upcoming Zoom meetings", Method: "GET", Path: "/users/me/meetings", Params: j(`{"page_size":{"type":"number","required":false,"desc":"Max meetings"}}`)},
		// Asana
		{PlatformID: "asana", ActionKey: "create_task", Name: "Create Task", Description: "Create an Asana task", WhenToUse: "When user asks to create a task in Asana", Method: "POST", Path: "/tasks", Params: j(`{"name":{"type":"string","required":true,"desc":"Task name"},"projects":{"type":"string","required":true,"desc":"Project GID"},"notes":{"type":"string","required":false,"desc":"Task description"}}`)},
		// ClickUp
		{PlatformID: "clickup", ActionKey: "create_task", Name: "Create Task", Description: "Create a ClickUp task", WhenToUse: "When user asks to create a task in ClickUp", Method: "POST", Path: "/list/{list_id}/task", Params: j(`{"list_id":{"type":"string","required":true,"desc":"List ID"},"name":{"type":"string","required":true,"desc":"Task name"},"description":{"type":"string","required":false,"desc":"Description"}}`)},
		// Linear
		{PlatformID: "linear", ActionKey: "create_issue", Name: "Create Issue", Description: "Create a Linear issue", WhenToUse: "When user asks to create a Linear issue or ticket", Method: "POST", Path: "/graphql", Params: j(`{"title":{"type":"string","required":true,"desc":"Issue title"},"description":{"type":"string","required":false,"desc":"Description"},"teamId":{"type":"string","required":true,"desc":"Team ID"}}`)},
		// Todoist
		{PlatformID: "todoist", ActionKey: "create_task", Name: "Create Task", Description: "Create a Todoist task", WhenToUse: "When user asks to add a to-do or create a Todoist task", Method: "POST", Path: "/tasks", Params: j(`{"content":{"type":"string","required":true,"desc":"Task content"},"due_string":{"type":"string","required":false,"desc":"Due date like 'tomorrow' or '2024-01-15'"},"priority":{"type":"number","required":false,"desc":"1-4, 4=urgent"}}`)},
		// Zendesk
		{PlatformID: "zendesk", ActionKey: "create_ticket", Name: "Create Ticket", Description: "Create a Zendesk support ticket", WhenToUse: "When user asks to create a support ticket in Zendesk", Method: "POST", Path: "/tickets.json", Params: j(`{"subject":{"type":"string","required":true,"desc":"Ticket subject"},"description":{"type":"string","required":true,"desc":"Ticket description"},"priority":{"type":"string","required":false,"desc":"low, normal, high, urgent"}}`)},
		// Intercom
		{PlatformID: "intercom", ActionKey: "send_message", Name: "Send Message", Description: "Send an Intercom message", WhenToUse: "When user asks to message someone on Intercom", Method: "POST", Path: "/messages", Params: j(`{"from":{"type":"object","required":true,"desc":"{type:'admin',id:'admin_id'}"},"to":{"type":"object","required":true,"desc":"{type:'user',id:'user_id'}"},"body":{"type":"string","required":true,"desc":"Message body"}}`)},
		// Mailchimp
		{PlatformID: "mailchimp", ActionKey: "add_subscriber", Name: "Add Subscriber", Description: "Add a subscriber to a Mailchimp list", WhenToUse: "When user asks to add someone to a mailing list or newsletter", Method: "POST", Path: "/lists/{list_id}/members", Params: j(`{"list_id":{"type":"string","required":true,"desc":"List/audience ID"},"email_address":{"type":"string","required":true,"desc":"Email"},"status":{"type":"string","required":false,"desc":"subscribed, pending"}}`)},
		// SendGrid
		{PlatformID: "sendgrid", ActionKey: "send_email", Name: "Send Email", Description: "Send an email via SendGrid", WhenToUse: "When user asks to send a transactional email via SendGrid", Method: "POST", Path: "/mail/send", Params: j(`{"to":{"type":"string","required":true,"desc":"Recipient email"},"subject":{"type":"string","required":true,"desc":"Subject"},"content":{"type":"string","required":true,"desc":"Email body HTML"}}`)},
		// Twilio
		{PlatformID: "twilio", ActionKey: "send_sms", Name: "Send SMS", Description: "Send an SMS via Twilio", WhenToUse: "When user asks to send a text message or SMS", Method: "POST", Path: "/Accounts/{account_sid}/Messages.json", Params: j(`{"To":{"type":"string","required":true,"desc":"Phone number with country code"},"Body":{"type":"string","required":true,"desc":"SMS text"},"From":{"type":"string","required":true,"desc":"Twilio phone number"}}`)},
		// PayPal
		{PlatformID: "paypal", ActionKey: "create_invoice", Name: "Create Invoice", Description: "Create a PayPal invoice", WhenToUse: "When user asks to create a PayPal invoice", Method: "POST", Path: "/invoicing/invoices", Params: j(`{"recipient_email":{"type":"string","required":true,"desc":"Recipient email"},"amount":{"type":"number","required":true,"desc":"Amount"},"currency":{"type":"string","required":false,"desc":"Currency code, default USD"}}`)},
		// Calendly
		{PlatformID: "calendly", ActionKey: "list_events", Name: "List Events", Description: "List scheduled Calendly events", WhenToUse: "When user asks about Calendly bookings or scheduled meetings", Method: "GET", Path: "/scheduled_events", Params: j(`{"count":{"type":"number","required":false,"desc":"Max events"},"status":{"type":"string","required":false,"desc":"active or canceled"}}`)},
		// Dropbox
		{PlatformID: "dropbox", ActionKey: "list_files", Name: "List Files", Description: "List files in a Dropbox folder", WhenToUse: "When user asks to see Dropbox files or browse folders", Method: "POST", Path: "/files/list_folder", Params: j(`{"path":{"type":"string","required":true,"desc":"Folder path like /Documents"}}`)},
		// Pipedrive
		{PlatformID: "pipedrive", ActionKey: "create_deal", Name: "Create Deal", Description: "Create a deal in Pipedrive", WhenToUse: "When user asks to create a deal or opportunity in Pipedrive", Method: "POST", Path: "/deals", Params: j(`{"title":{"type":"string","required":true,"desc":"Deal title"},"value":{"type":"number","required":false,"desc":"Deal value"},"currency":{"type":"string","required":false,"desc":"Currency code"}}`)},
		// Zoho CRM
		{PlatformID: "zoho-crm", ActionKey: "create_lead", Name: "Create Lead", Description: "Create a lead in Zoho CRM", WhenToUse: "When user asks to add a lead to Zoho", Method: "POST", Path: "/Leads", Params: j(`{"First_Name":{"type":"string","required":false,"desc":"First name"},"Last_Name":{"type":"string","required":true,"desc":"Last name"},"Email":{"type":"string","required":false,"desc":"Email"},"Company":{"type":"string","required":false,"desc":"Company"}}`)},
		// ElevenLabs
		{PlatformID: "elevenlabs", ActionKey: "text_to_speech", Name: "Text to Speech", Description: "Convert text to speech audio", WhenToUse: "When user asks to generate speech, read text aloud, or create audio", Method: "POST", Path: "/text-to-speech/{voice_id}", Params: j(`{"voice_id":{"type":"string","required":true,"desc":"Voice ID"},"text":{"type":"string","required":true,"desc":"Text to convert"},"model_id":{"type":"string","required":false,"desc":"Model ID, default eleven_monolingual_v1"}}`)},
		// Resend
		{PlatformID: "resend", ActionKey: "send_email", Name: "Send Email", Description: "Send an email via Resend", WhenToUse: "When user asks to send email via Resend", Method: "POST", Path: "/emails", Params: j(`{"from":{"type":"string","required":true,"desc":"Sender email"},"to":{"type":"string","required":true,"desc":"Recipient email"},"subject":{"type":"string","required":true,"desc":"Subject"},"html":{"type":"string","required":true,"desc":"Email body HTML"}}`)},
	}

	for _, p := range platforms {
		if err := ks.UpsertPlatform(ctx, p); err != nil {
			slog.Warn("seed.expanded_platform_failed", "id", p.ID, "error", err)
		}
	}
	for _, a := range actions {
		if err := ks.UpsertAction(ctx, a); err != nil {
			slog.Warn("seed.expanded_action_failed", "platform", a.PlatformID, "action", a.ActionKey, "error", err)
		}
	}
	slog.Info("seed.expanded_complete", "platforms", len(platforms), "actions", len(actions))
}

// SeedTopConnectors adds 20+ business tool platforms with Pipedream-backed actions.
// Only platforms not already in SeedPlatforms or SeedExpandedPlatforms are included.
func SeedTopConnectors(ctx context.Context, ks *KnowledgeStore) {
	platforms := []Platform{
		// CRM
		{ID: "close-crm", Name: "Close CRM", Category: "crm", Description: "CRM for inside sales teams with built-in calling and email", Icon: "phone-call", AuthType: "api_key", AuthConfig: j(`{"header_name":"Authorization","prefix":"Basic "}`), BaseURL: "https://api.close.com/api/v1", DocsURL: "https://developer.close.com/", Enabled: true},

		// Dev/Project
		{ID: "gitlab", Name: "GitLab", Category: "dev", Description: "DevOps platform for source control, CI/CD, and project management", Icon: "git-branch", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://gitlab.com/api/v4", DocsURL: "https://docs.gitlab.com/ee/api/", Enabled: true},
		{ID: "bitbucket", Name: "Bitbucket", Category: "dev", Description: "Git repository hosting with CI/CD pipelines", Icon: "git-merge", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://api.bitbucket.org/2.0", DocsURL: "https://developer.atlassian.com/cloud/bitbucket/rest/intro/", Enabled: true},

		// Marketing
		{ID: "klaviyo", Name: "Klaviyo", Category: "marketing", Description: "Email and SMS marketing automation for ecommerce", Icon: "mail", AuthType: "api_key", AuthConfig: j(`{"header_name":"Authorization","prefix":"Klaviyo-API-Key "}`), BaseURL: "https://a.klaviyo.com/api", DocsURL: "https://developers.klaviyo.com/en/reference/api_overview", Enabled: true},
		{ID: "activecampaign", Name: "ActiveCampaign", Category: "marketing", Description: "Email marketing, automation, and CRM platform", Icon: "zap", AuthType: "api_key", AuthConfig: j(`{"header_name":"Api-Token","prefix":""}`), BaseURL: "https://{account}.api-us1.com/api/3", DocsURL: "https://developers.activecampaign.com/reference", Enabled: true},
		{ID: "brevo", Name: "Brevo", Category: "marketing", Description: "Email, SMS, and marketing automation platform (formerly Sendinblue)", Icon: "send", AuthType: "api_key", AuthConfig: j(`{"header_name":"api-key","prefix":""}`), BaseURL: "https://api.brevo.com/v3", DocsURL: "https://developers.brevo.com/reference", Enabled: true},

		// Finance/Payments
		{ID: "square", Name: "Square", Category: "finance", Description: "Payment processing, POS, and business management", Icon: "credit-card", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://connect.squareup.com/v2", DocsURL: "https://developer.squareup.com/reference/square", Enabled: true},

		// Ecommerce
		{ID: "woocommerce", Name: "WooCommerce", Category: "ecommerce", Description: "Open-source ecommerce plugin for WordPress", Icon: "shopping-cart", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://{site}/wp-json/wc/v3", DocsURL: "https://woocommerce.github.io/woocommerce-rest-api-docs/", Enabled: true},
		{ID: "bigcommerce", Name: "BigCommerce", Category: "ecommerce", Description: "Enterprise ecommerce platform for growing businesses", Icon: "shopping-bag", AuthType: "api_key", AuthConfig: j(`{"header_name":"X-Auth-Token","prefix":""}`), BaseURL: "https://api.bigcommerce.com/stores/{store_hash}/v3", DocsURL: "https://developer.bigcommerce.com/docs/rest-management", Enabled: true},

		// Analytics
		{ID: "google-analytics", Name: "Google Analytics", Category: "analytics", Description: "Web analytics for tracking website traffic and user behavior", Icon: "bar-chart-2", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://analyticsdata.googleapis.com/v1beta", DocsURL: "https://developers.google.com/analytics/devguides/reporting/data/v1", Enabled: true},
		{ID: "mixpanel", Name: "Mixpanel", Category: "analytics", Description: "Product analytics for tracking user interactions and funnels", Icon: "pie-chart", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://mixpanel.com/api/2.0", DocsURL: "https://developer.mixpanel.com/reference", Enabled: true},
		{ID: "amplitude", Name: "Amplitude", Category: "analytics", Description: "Digital analytics platform for product and growth teams", Icon: "trending-up", AuthType: "api_key", AuthConfig: j(`{"header_name":"Authorization","prefix":"Api-Key "}`), BaseURL: "https://amplitude.com/api/2", DocsURL: "https://www.docs.developers.amplitude.com/analytics/apis/", Enabled: true},

		// HR/Recruiting
		{ID: "bamboohr", Name: "BambooHR", Category: "hr", Description: "HR software for small and medium businesses", Icon: "users", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://api.bamboohr.com/api/gateway.php/{company}", DocsURL: "https://documentation.bamboohr.com/reference", Enabled: true},
		{ID: "greenhouse", Name: "Greenhouse", Category: "hr", Description: "Applicant tracking and recruiting platform", Icon: "user-plus", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://harvest.greenhouse.io/v1", DocsURL: "https://developers.greenhouse.io/harvest.html", Enabled: true},
		{ID: "lever", Name: "Lever", Category: "hr", Description: "Recruiting software and applicant tracking system", Icon: "briefcase", AuthType: "basic", AuthConfig: j(`{}`), BaseURL: "https://api.lever.co/v1", DocsURL: "https://hire.lever.co/developer/documentation", Enabled: true},

		// Databases/No-code
		{ID: "firebase", Name: "Firebase", Category: "database", Description: "Google cloud platform for app development with Firestore and Realtime DB", Icon: "database", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://firestore.googleapis.com/v1", DocsURL: "https://firebase.google.com/docs/firestore/reference/rest", Enabled: true},

		// Automation
		{ID: "zapier-webhooks", Name: "Zapier Webhooks", Category: "automation", Description: "Trigger Zapier workflows via webhooks", Icon: "zap", AuthType: "none", AuthConfig: j(`{}`), BaseURL: "https://hooks.zapier.com", DocsURL: "https://zapier.com/apps/webhook/integrations", Enabled: true},
		{ID: "make", Name: "Make (Integromat)", Category: "automation", Description: "Visual automation platform for connecting apps and workflows", Icon: "repeat", AuthType: "api_key", AuthConfig: j(`{"header_name":"Authorization","prefix":"Token "}`), BaseURL: "https://hook.us1.make.com", DocsURL: "https://www.make.com/en/api-documentation", Enabled: true},
		{ID: "n8n", Name: "n8n", Category: "automation", Description: "Open-source workflow automation tool", Icon: "git-merge", AuthType: "none", AuthConfig: j(`{}`), BaseURL: "https://{instance}.app.n8n.cloud/webhook", DocsURL: "https://docs.n8n.io/api/", Enabled: true},

		// Other Popular
		{ID: "webflow", Name: "Webflow", Category: "productivity", Description: "Visual web design and CMS platform", Icon: "globe", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.webflow.com/v2", DocsURL: "https://developers.webflow.com/reference", Enabled: true},
		{ID: "contentful", Name: "Contentful", Category: "productivity", Description: "Headless CMS for managing digital content", Icon: "file-text", AuthType: "bearer", AuthConfig: j(`{}`), BaseURL: "https://api.contentful.com", DocsURL: "https://www.contentful.com/developers/docs/references/content-management-api/", Enabled: true},
		{ID: "google-search-console", Name: "Google Search Console", Category: "analytics", Description: "Monitor search performance, indexing, and site health", Icon: "search", AuthType: "oauth2", AuthConfig: j(`{"provider":"google"}`), BaseURL: "https://searchconsole.googleapis.com/v1", DocsURL: "https://developers.google.com/webmaster-tools/v1/api_reference_index", Enabled: true},
	}

	actions := []ActionDef{
		// Close CRM
		{PlatformID: "close-crm", ActionKey: "create_lead", Name: "Create Lead", Description: "Create a new lead in Close CRM", WhenToUse: "When user asks to add a lead, prospect, or company to Close CRM", Method: "POST", Path: "/connect/actions/run", Params: j(`{"name":{"type":"string","required":true,"desc":"Lead/company name"},"contacts":{"type":"array","required":false,"desc":"Array of contact objects with name and email"}}`), ResponseDesc: "Lead ID and URL", ExecutionBackend: "pipedream", PipedreamActionID: "close-create-lead"},
		{PlatformID: "close-crm", ActionKey: "search_leads", Name: "Search Leads", Description: "Search for leads in Close CRM", WhenToUse: "When user asks to find a lead, look up a company, or search contacts in Close", Method: "POST", Path: "/connect/actions/run", Params: j(`{"query":{"type":"string","required":true,"desc":"Search query — name, email, or phone"}}`), ResponseDesc: "Array of matching leads", ExecutionBackend: "pipedream", PipedreamActionID: "close-search-leads"},
		{PlatformID: "close-crm", ActionKey: "log_activity", Name: "Log Activity", Description: "Log a call, email, or note activity on a lead", WhenToUse: "When user asks to log a call, note an interaction, or record activity in Close CRM", Method: "POST", Path: "/connect/actions/run", Params: j(`{"lead_id":{"type":"string","required":true,"desc":"Lead ID"},"type":{"type":"string","required":true,"desc":"Activity type: call, email, note"},"note":{"type":"string","required":true,"desc":"Activity description or content"}}`), ResponseDesc: "Activity ID", ExecutionBackend: "pipedream", PipedreamActionID: "close-create-activity"},

		// GitLab
		{PlatformID: "gitlab", ActionKey: "create_issue", Name: "Create Issue", Description: "Create an issue in a GitLab project", WhenToUse: "When user asks to create a GitLab issue, file a bug, or add a task in GitLab", Method: "POST", Path: "/connect/actions/run", Params: j(`{"project_id":{"type":"string","required":true,"desc":"GitLab project ID or path"},"title":{"type":"string","required":true,"desc":"Issue title"},"description":{"type":"string","required":false,"desc":"Issue description in Markdown"},"labels":{"type":"string","required":false,"desc":"Comma-separated label names"}}`), ResponseDesc: "Issue ID, IID, and web URL", ExecutionBackend: "pipedream", PipedreamActionID: "gitlab-create-issue"},
		{PlatformID: "gitlab", ActionKey: "create_merge_request", Name: "Create Merge Request", Description: "Create a merge request in GitLab", WhenToUse: "When user asks to create a merge request, MR, or pull request in GitLab", Method: "POST", Path: "/connect/actions/run", Params: j(`{"project_id":{"type":"string","required":true,"desc":"GitLab project ID or path"},"title":{"type":"string","required":true,"desc":"MR title"},"source_branch":{"type":"string","required":true,"desc":"Source branch name"},"target_branch":{"type":"string","required":true,"desc":"Target branch name"},"description":{"type":"string","required":false,"desc":"MR description"}}`), ResponseDesc: "Merge request IID and URL", ExecutionBackend: "pipedream", PipedreamActionID: "gitlab-create-merge-request"},
		{PlatformID: "gitlab", ActionKey: "list_pipelines", Name: "List Pipelines", Description: "List CI/CD pipelines for a GitLab project", WhenToUse: "When user asks about GitLab pipelines, CI status, or build results", Method: "POST", Path: "/connect/actions/run", Params: j(`{"project_id":{"type":"string","required":true,"desc":"GitLab project ID or path"},"status":{"type":"string","required":false,"desc":"Filter by status: running, pending, success, failed"}}`), ResponseDesc: "Array of pipelines with ID, status, and ref", ExecutionBackend: "pipedream", PipedreamActionID: "gitlab-list-pipelines"},

		// Bitbucket
		{PlatformID: "bitbucket", ActionKey: "create_pull_request", Name: "Create Pull Request", Description: "Create a pull request in Bitbucket", WhenToUse: "When user asks to create a PR or pull request in Bitbucket", Method: "POST", Path: "/connect/actions/run", Params: j(`{"workspace":{"type":"string","required":true,"desc":"Bitbucket workspace slug"},"repo_slug":{"type":"string","required":true,"desc":"Repository slug"},"title":{"type":"string","required":true,"desc":"PR title"},"source_branch":{"type":"string","required":true,"desc":"Source branch"},"destination_branch":{"type":"string","required":false,"desc":"Target branch, defaults to main"}}`), ResponseDesc: "Pull request ID and URL", ExecutionBackend: "pipedream", PipedreamActionID: "bitbucket-create-pull-request"},
		{PlatformID: "bitbucket", ActionKey: "list_repos", Name: "List Repositories", Description: "List repositories in a Bitbucket workspace", WhenToUse: "When user asks to list repos, see repositories, or browse Bitbucket projects", Method: "POST", Path: "/connect/actions/run", Params: j(`{"workspace":{"type":"string","required":true,"desc":"Bitbucket workspace slug"}}`), ResponseDesc: "Array of repositories with name, slug, and URL", ExecutionBackend: "pipedream", PipedreamActionID: "bitbucket-list-repos"},
		{PlatformID: "bitbucket", ActionKey: "create_issue", Name: "Create Issue", Description: "Create an issue in a Bitbucket repository", WhenToUse: "When user asks to create a Bitbucket issue or report a bug in Bitbucket", Method: "POST", Path: "/connect/actions/run", Params: j(`{"workspace":{"type":"string","required":true,"desc":"Bitbucket workspace slug"},"repo_slug":{"type":"string","required":true,"desc":"Repository slug"},"title":{"type":"string","required":true,"desc":"Issue title"},"content":{"type":"string","required":false,"desc":"Issue description"},"priority":{"type":"string","required":false,"desc":"trivial, minor, major, critical, blocker"}}`), ResponseDesc: "Issue ID and URL", ExecutionBackend: "pipedream", PipedreamActionID: "bitbucket-create-issue"},

		// Klaviyo
		{PlatformID: "klaviyo", ActionKey: "add_profile", Name: "Add Profile", Description: "Create or update a profile in Klaviyo", WhenToUse: "When user asks to add a subscriber, create a contact, or add someone to Klaviyo", Method: "POST", Path: "/connect/actions/run", Params: j(`{"email":{"type":"string","required":true,"desc":"Contact email address"},"first_name":{"type":"string","required":false,"desc":"First name"},"last_name":{"type":"string","required":false,"desc":"Last name"},"phone_number":{"type":"string","required":false,"desc":"Phone number with country code"}}`), ResponseDesc: "Profile ID", ExecutionBackend: "pipedream", PipedreamActionID: "klaviyo-create-profile"},
		{PlatformID: "klaviyo", ActionKey: "create_event", Name: "Create Event", Description: "Track a custom event for a Klaviyo profile", WhenToUse: "When user asks to track an event, log an action, or record activity in Klaviyo", Method: "POST", Path: "/connect/actions/run", Params: j(`{"event_name":{"type":"string","required":true,"desc":"Event name like Placed Order or Viewed Product"},"email":{"type":"string","required":true,"desc":"Profile email"},"properties":{"type":"object","required":false,"desc":"Event properties as key-value pairs"}}`), ResponseDesc: "Event ID", ExecutionBackend: "pipedream", PipedreamActionID: "klaviyo-create-event"},
		{PlatformID: "klaviyo", ActionKey: "send_campaign", Name: "Send Campaign", Description: "Send or schedule a Klaviyo campaign", WhenToUse: "When user asks to send a Klaviyo campaign or blast an email to a list", Method: "POST", Path: "/connect/actions/run", Params: j(`{"campaign_id":{"type":"string","required":true,"desc":"Campaign ID to send"},"send_time":{"type":"string","required":false,"desc":"ISO 8601 datetime to schedule, omit for immediate"}}`), ResponseDesc: "Campaign send status", ExecutionBackend: "pipedream", PipedreamActionID: "klaviyo-send-campaign"},

		// ActiveCampaign
		{PlatformID: "activecampaign", ActionKey: "create_contact", Name: "Create Contact", Description: "Create a contact in ActiveCampaign", WhenToUse: "When user asks to add a contact, subscriber, or lead to ActiveCampaign", Method: "POST", Path: "/connect/actions/run", Params: j(`{"email":{"type":"string","required":true,"desc":"Contact email"},"first_name":{"type":"string","required":false,"desc":"First name"},"last_name":{"type":"string","required":false,"desc":"Last name"},"phone":{"type":"string","required":false,"desc":"Phone number"}}`), ResponseDesc: "Contact ID", ExecutionBackend: "pipedream", PipedreamActionID: "activecampaign-create-contact"},
		{PlatformID: "activecampaign", ActionKey: "add_tag", Name: "Add Tag", Description: "Add a tag to a contact in ActiveCampaign", WhenToUse: "When user asks to tag a contact, label a subscriber, or categorize someone in ActiveCampaign", Method: "POST", Path: "/connect/actions/run", Params: j(`{"contact_id":{"type":"string","required":true,"desc":"Contact ID"},"tag":{"type":"string","required":true,"desc":"Tag name to add"}}`), ResponseDesc: "Contact tag ID", ExecutionBackend: "pipedream", PipedreamActionID: "activecampaign-add-tag-to-contact"},
		{PlatformID: "activecampaign", ActionKey: "send_email", Name: "Send Email", Description: "Send a campaign email via ActiveCampaign", WhenToUse: "When user asks to send an email campaign or newsletter through ActiveCampaign", Method: "POST", Path: "/connect/actions/run", Params: j(`{"campaign_id":{"type":"string","required":true,"desc":"Campaign ID to send"}}`), ResponseDesc: "Campaign send status", ExecutionBackend: "pipedream", PipedreamActionID: "activecampaign-send-campaign"},

		// Brevo
		{PlatformID: "brevo", ActionKey: "send_email", Name: "Send Email", Description: "Send a transactional email via Brevo", WhenToUse: "When user asks to send an email through Brevo or Sendinblue", Method: "POST", Path: "/connect/actions/run", Params: j(`{"to":{"type":"string","required":true,"desc":"Recipient email"},"subject":{"type":"string","required":true,"desc":"Email subject"},"html_content":{"type":"string","required":true,"desc":"Email body HTML"},"sender_email":{"type":"string","required":true,"desc":"Sender email address"}}`), ResponseDesc: "Message ID", ExecutionBackend: "pipedream", PipedreamActionID: "brevo-send-transactional-email"},
		{PlatformID: "brevo", ActionKey: "create_contact", Name: "Create Contact", Description: "Create a contact in Brevo", WhenToUse: "When user asks to add a subscriber or contact to Brevo or Sendinblue", Method: "POST", Path: "/connect/actions/run", Params: j(`{"email":{"type":"string","required":true,"desc":"Contact email"},"first_name":{"type":"string","required":false,"desc":"First name"},"last_name":{"type":"string","required":false,"desc":"Last name"},"list_ids":{"type":"array","required":false,"desc":"Array of list IDs to add contact to"}}`), ResponseDesc: "Contact ID", ExecutionBackend: "pipedream", PipedreamActionID: "brevo-create-contact"},
		{PlatformID: "brevo", ActionKey: "add_to_list", Name: "Add to List", Description: "Add a contact to a Brevo list", WhenToUse: "When user asks to add someone to a mailing list in Brevo or Sendinblue", Method: "POST", Path: "/connect/actions/run", Params: j(`{"list_id":{"type":"string","required":true,"desc":"List ID"},"emails":{"type":"array","required":true,"desc":"Array of email addresses to add"}}`), ResponseDesc: "Success status", ExecutionBackend: "pipedream", PipedreamActionID: "brevo-add-contact-to-list"},

		// Square
		{PlatformID: "square", ActionKey: "create_payment", Name: "Create Payment", Description: "Process a payment through Square", WhenToUse: "When user asks to charge a customer, process a payment, or take a payment via Square", Method: "POST", Path: "/connect/actions/run", Params: j(`{"amount":{"type":"number","required":true,"desc":"Amount in smallest currency unit (cents)"},"currency":{"type":"string","required":true,"desc":"Currency code like USD"},"source_id":{"type":"string","required":true,"desc":"Payment source (card nonce or customer card ID)"}}`), ResponseDesc: "Payment ID and status", ExecutionBackend: "pipedream", PipedreamActionID: "square-create-payment"},
		{PlatformID: "square", ActionKey: "create_customer", Name: "Create Customer", Description: "Create a customer in Square", WhenToUse: "When user asks to add a customer to Square or save customer details", Method: "POST", Path: "/connect/actions/run", Params: j(`{"given_name":{"type":"string","required":true,"desc":"First name"},"family_name":{"type":"string","required":false,"desc":"Last name"},"email_address":{"type":"string","required":false,"desc":"Email"},"phone_number":{"type":"string","required":false,"desc":"Phone number"}}`), ResponseDesc: "Customer ID", ExecutionBackend: "pipedream", PipedreamActionID: "square-create-customer"},
		{PlatformID: "square", ActionKey: "list_orders", Name: "List Orders", Description: "List orders from Square", WhenToUse: "When user asks about Square orders, recent sales, or transactions", Method: "POST", Path: "/connect/actions/run", Params: j(`{"location_id":{"type":"string","required":true,"desc":"Square location ID"},"limit":{"type":"number","required":false,"desc":"Max orders to return"}}`), ResponseDesc: "Array of orders with ID, total, and status", ExecutionBackend: "pipedream", PipedreamActionID: "square-list-orders"},

		// WooCommerce
		{PlatformID: "woocommerce", ActionKey: "create_product", Name: "Create Product", Description: "Create a product in WooCommerce", WhenToUse: "When user asks to add a product to WooCommerce store or create a listing", Method: "POST", Path: "/connect/actions/run", Params: j(`{"name":{"type":"string","required":true,"desc":"Product name"},"regular_price":{"type":"string","required":true,"desc":"Product price"},"description":{"type":"string","required":false,"desc":"Product description"},"type":{"type":"string","required":false,"desc":"simple, grouped, variable, external"}}`), ResponseDesc: "Product ID and permalink", ExecutionBackend: "pipedream", PipedreamActionID: "woocommerce-create-product"},
		{PlatformID: "woocommerce", ActionKey: "list_orders", Name: "List Orders", Description: "List WooCommerce orders", WhenToUse: "When user asks about WooCommerce orders, store sales, or order status", Method: "POST", Path: "/connect/actions/run", Params: j(`{"status":{"type":"string","required":false,"desc":"pending, processing, completed, on-hold"},"per_page":{"type":"number","required":false,"desc":"Max orders, default 10"}}`), ResponseDesc: "Array of orders with ID, status, and total", ExecutionBackend: "pipedream", PipedreamActionID: "woocommerce-list-orders"},
		{PlatformID: "woocommerce", ActionKey: "update_order", Name: "Update Order", Description: "Update a WooCommerce order status", WhenToUse: "When user asks to update an order, change order status, or mark order as shipped in WooCommerce", Method: "POST", Path: "/connect/actions/run", Params: j(`{"order_id":{"type":"string","required":true,"desc":"Order ID"},"status":{"type":"string","required":true,"desc":"New status: pending, processing, completed, cancelled"}}`), ResponseDesc: "Updated order details", ExecutionBackend: "pipedream", PipedreamActionID: "woocommerce-update-order"},

		// BigCommerce
		{PlatformID: "bigcommerce", ActionKey: "create_product", Name: "Create Product", Description: "Create a product in BigCommerce", WhenToUse: "When user asks to add a product to BigCommerce or create a store listing", Method: "POST", Path: "/connect/actions/run", Params: j(`{"name":{"type":"string","required":true,"desc":"Product name"},"price":{"type":"number","required":true,"desc":"Product price"},"type":{"type":"string","required":true,"desc":"physical or digital"},"weight":{"type":"number","required":true,"desc":"Product weight"}}`), ResponseDesc: "Product ID", ExecutionBackend: "pipedream", PipedreamActionID: "bigcommerce-create-product"},
		{PlatformID: "bigcommerce", ActionKey: "list_orders", Name: "List Orders", Description: "List BigCommerce orders", WhenToUse: "When user asks about BigCommerce orders or store sales", Method: "POST", Path: "/connect/actions/run", Params: j(`{"status_id":{"type":"number","required":false,"desc":"Filter by status ID"},"limit":{"type":"number","required":false,"desc":"Max orders, default 50"}}`), ResponseDesc: "Array of orders with ID, status, and total", ExecutionBackend: "pipedream", PipedreamActionID: "bigcommerce-list-orders"},
		{PlatformID: "bigcommerce", ActionKey: "update_order", Name: "Update Order", Description: "Update a BigCommerce order", WhenToUse: "When user asks to update order status or modify an order in BigCommerce", Method: "POST", Path: "/connect/actions/run", Params: j(`{"order_id":{"type":"string","required":true,"desc":"Order ID"},"status_id":{"type":"number","required":true,"desc":"New status ID"}}`), ResponseDesc: "Updated order details", ExecutionBackend: "pipedream", PipedreamActionID: "bigcommerce-update-order"},

		// Google Analytics
		{PlatformID: "google-analytics", ActionKey: "get_report", Name: "Get Report", Description: "Run a Google Analytics report", WhenToUse: "When user asks for analytics data, website traffic, page views, or visitor stats", Method: "POST", Path: "/connect/actions/run", Params: j(`{"property_id":{"type":"string","required":true,"desc":"GA4 property ID"},"start_date":{"type":"string","required":true,"desc":"Start date YYYY-MM-DD"},"end_date":{"type":"string","required":true,"desc":"End date YYYY-MM-DD"},"metrics":{"type":"array","required":true,"desc":"Metrics like sessions, pageViews, activeUsers"},"dimensions":{"type":"array","required":false,"desc":"Dimensions like date, country, pagePath"}}`), ResponseDesc: "Report rows with metric values", ExecutionBackend: "pipedream", PipedreamActionID: "google_analytics-run-report"},
		{PlatformID: "google-analytics", ActionKey: "list_accounts", Name: "List Accounts", Description: "List Google Analytics accounts and properties", WhenToUse: "When user asks what analytics accounts or properties are available", Method: "POST", Path: "/connect/actions/run", Params: j(`{}`), ResponseDesc: "Array of accounts with property IDs", ExecutionBackend: "pipedream", PipedreamActionID: "google_analytics-list-accounts"},

		// Mixpanel
		{PlatformID: "mixpanel", ActionKey: "track_event", Name: "Track Event", Description: "Track an event in Mixpanel", WhenToUse: "When user asks to track an event, log user activity, or send data to Mixpanel", Method: "POST", Path: "/connect/actions/run", Params: j(`{"event":{"type":"string","required":true,"desc":"Event name"},"distinct_id":{"type":"string","required":true,"desc":"User identifier"},"properties":{"type":"object","required":false,"desc":"Event properties as key-value pairs"}}`), ResponseDesc: "Success status", ExecutionBackend: "pipedream", PipedreamActionID: "mixpanel-track-event"},
		{PlatformID: "mixpanel", ActionKey: "get_funnel", Name: "Get Funnel", Description: "Get funnel analysis data from Mixpanel", WhenToUse: "When user asks about funnel conversion, drop-off rates, or funnel metrics in Mixpanel", Method: "POST", Path: "/connect/actions/run", Params: j(`{"funnel_id":{"type":"string","required":true,"desc":"Funnel ID"},"from_date":{"type":"string","required":true,"desc":"Start date YYYY-MM-DD"},"to_date":{"type":"string","required":true,"desc":"End date YYYY-MM-DD"}}`), ResponseDesc: "Funnel steps with conversion rates", ExecutionBackend: "pipedream", PipedreamActionID: "mixpanel-get-funnel"},

		// Amplitude
		{PlatformID: "amplitude", ActionKey: "track_event", Name: "Track Event", Description: "Track an event in Amplitude", WhenToUse: "When user asks to track an event, log activity, or send analytics to Amplitude", Method: "POST", Path: "/connect/actions/run", Params: j(`{"event_type":{"type":"string","required":true,"desc":"Event name"},"user_id":{"type":"string","required":true,"desc":"User identifier"},"event_properties":{"type":"object","required":false,"desc":"Event properties"}}`), ResponseDesc: "Success status", ExecutionBackend: "pipedream", PipedreamActionID: "amplitude-track-event"},
		{PlatformID: "amplitude", ActionKey: "get_cohorts", Name: "Get Cohorts", Description: "List cohorts from Amplitude", WhenToUse: "When user asks about user cohorts, segments, or audience groups in Amplitude", Method: "POST", Path: "/connect/actions/run", Params: j(`{}`), ResponseDesc: "Array of cohorts with ID, name, and size", ExecutionBackend: "pipedream", PipedreamActionID: "amplitude-list-cohorts"},

		// BambooHR
		{PlatformID: "bamboohr", ActionKey: "list_employees", Name: "List Employees", Description: "List employees from BambooHR", WhenToUse: "When user asks to see the employee directory, list staff, or get team members from BambooHR", Method: "POST", Path: "/connect/actions/run", Params: j(`{}`), ResponseDesc: "Array of employees with name, department, and job title", ExecutionBackend: "pipedream", PipedreamActionID: "bamboohr-list-employees"},
		{PlatformID: "bamboohr", ActionKey: "create_employee", Name: "Create Employee", Description: "Add a new employee to BambooHR", WhenToUse: "When user asks to add a new hire, create an employee record, or onboard someone in BambooHR", Method: "POST", Path: "/connect/actions/run", Params: j(`{"first_name":{"type":"string","required":true,"desc":"First name"},"last_name":{"type":"string","required":true,"desc":"Last name"},"email":{"type":"string","required":false,"desc":"Work email"},"department":{"type":"string","required":false,"desc":"Department name"},"job_title":{"type":"string","required":false,"desc":"Job title"}}`), ResponseDesc: "Employee ID", ExecutionBackend: "pipedream", PipedreamActionID: "bamboohr-create-employee"},
		{PlatformID: "bamboohr", ActionKey: "request_time_off", Name: "Request Time Off", Description: "Submit a time-off request in BambooHR", WhenToUse: "When user asks to request PTO, vacation, sick leave, or time off in BambooHR", Method: "POST", Path: "/connect/actions/run", Params: j(`{"employee_id":{"type":"string","required":true,"desc":"Employee ID"},"start_date":{"type":"string","required":true,"desc":"Start date YYYY-MM-DD"},"end_date":{"type":"string","required":true,"desc":"End date YYYY-MM-DD"},"time_off_type_id":{"type":"string","required":true,"desc":"Time off type ID"}}`), ResponseDesc: "Request ID and status", ExecutionBackend: "pipedream", PipedreamActionID: "bamboohr-create-time-off-request"},

		// Greenhouse
		{PlatformID: "greenhouse", ActionKey: "create_candidate", Name: "Create Candidate", Description: "Add a candidate to Greenhouse", WhenToUse: "When user asks to add a candidate, submit an applicant, or create a prospect in Greenhouse", Method: "POST", Path: "/connect/actions/run", Params: j(`{"first_name":{"type":"string","required":true,"desc":"First name"},"last_name":{"type":"string","required":true,"desc":"Last name"},"email":{"type":"string","required":true,"desc":"Email address"},"job_id":{"type":"string","required":false,"desc":"Job ID to apply to"}}`), ResponseDesc: "Candidate ID", ExecutionBackend: "pipedream", PipedreamActionID: "greenhouse-create-candidate"},
		{PlatformID: "greenhouse", ActionKey: "list_jobs", Name: "List Jobs", Description: "List open jobs in Greenhouse", WhenToUse: "When user asks about open positions, job listings, or available roles in Greenhouse", Method: "POST", Path: "/connect/actions/run", Params: j(`{"status":{"type":"string","required":false,"desc":"open, closed, or draft"}}`), ResponseDesc: "Array of jobs with title, department, and status", ExecutionBackend: "pipedream", PipedreamActionID: "greenhouse-list-jobs"},
		{PlatformID: "greenhouse", ActionKey: "advance_candidate", Name: "Advance Candidate", Description: "Move a candidate to the next stage in Greenhouse", WhenToUse: "When user asks to advance a candidate, move to next stage, or progress an applicant in Greenhouse", Method: "POST", Path: "/connect/actions/run", Params: j(`{"application_id":{"type":"string","required":true,"desc":"Application ID"},"from_stage_id":{"type":"string","required":false,"desc":"Current stage ID"}}`), ResponseDesc: "Updated application status", ExecutionBackend: "pipedream", PipedreamActionID: "greenhouse-advance-application"},

		// Lever
		{PlatformID: "lever", ActionKey: "create_opportunity", Name: "Create Opportunity", Description: "Create a candidate opportunity in Lever", WhenToUse: "When user asks to add a candidate, create an opportunity, or submit an applicant to Lever", Method: "POST", Path: "/connect/actions/run", Params: j(`{"name":{"type":"string","required":true,"desc":"Candidate full name"},"email":{"type":"string","required":true,"desc":"Candidate email"},"posting_id":{"type":"string","required":false,"desc":"Job posting ID"}}`), ResponseDesc: "Opportunity ID", ExecutionBackend: "pipedream", PipedreamActionID: "lever-create-opportunity"},
		{PlatformID: "lever", ActionKey: "list_candidates", Name: "List Candidates", Description: "List candidates in Lever", WhenToUse: "When user asks to see candidates, list applicants, or check the pipeline in Lever", Method: "POST", Path: "/connect/actions/run", Params: j(`{"posting_id":{"type":"string","required":false,"desc":"Filter by posting ID"},"stage_id":{"type":"string","required":false,"desc":"Filter by stage"}}`), ResponseDesc: "Array of candidates with name, email, and stage", ExecutionBackend: "pipedream", PipedreamActionID: "lever-list-opportunities"},

		// Firebase
		{PlatformID: "firebase", ActionKey: "set_document", Name: "Set Document", Description: "Create or overwrite a Firestore document", WhenToUse: "When user asks to write data to Firebase, create a document, or save to Firestore", Method: "POST", Path: "/connect/actions/run", Params: j(`{"collection":{"type":"string","required":true,"desc":"Firestore collection path"},"document_id":{"type":"string","required":false,"desc":"Document ID, auto-generated if omitted"},"data":{"type":"object","required":true,"desc":"Document fields as key-value pairs"}}`), ResponseDesc: "Document path and write time", ExecutionBackend: "pipedream", PipedreamActionID: "firebase_admin_sdk-create-document"},
		{PlatformID: "firebase", ActionKey: "get_document", Name: "Get Document", Description: "Retrieve a Firestore document", WhenToUse: "When user asks to read from Firebase, get a document, or fetch data from Firestore", Method: "POST", Path: "/connect/actions/run", Params: j(`{"collection":{"type":"string","required":true,"desc":"Firestore collection path"},"document_id":{"type":"string","required":true,"desc":"Document ID"}}`), ResponseDesc: "Document fields and metadata", ExecutionBackend: "pipedream", PipedreamActionID: "firebase_admin_sdk-get-document"},
		{PlatformID: "firebase", ActionKey: "query_collection", Name: "Query Collection", Description: "Query documents in a Firestore collection", WhenToUse: "When user asks to search Firebase, query Firestore, or find documents matching criteria", Method: "POST", Path: "/connect/actions/run", Params: j(`{"collection":{"type":"string","required":true,"desc":"Firestore collection path"},"field":{"type":"string","required":true,"desc":"Field to filter on"},"operator":{"type":"string","required":true,"desc":"Comparison: ==, !=, <, >, <=, >=, in, array-contains"},"value":{"type":"string","required":true,"desc":"Value to compare against"}}`), ResponseDesc: "Array of matching documents", ExecutionBackend: "pipedream", PipedreamActionID: "firebase_admin_sdk-query-firestore"},

		// Zapier Webhooks
		{PlatformID: "zapier-webhooks", ActionKey: "trigger_webhook", Name: "Trigger Webhook", Description: "Trigger a Zapier workflow via webhook", WhenToUse: "When user asks to trigger a Zapier zap, run a Zapier automation, or send data to a Zapier webhook", Method: "POST", Path: "/connect/actions/run", Params: j(`{"webhook_url":{"type":"string","required":true,"desc":"Zapier webhook URL"},"data":{"type":"object","required":false,"desc":"Payload data as key-value pairs"}}`), ResponseDesc: "Webhook trigger confirmation", ExecutionBackend: "pipedream", PipedreamActionID: "zapier-trigger-webhook"},

		// Make (Integromat)
		{PlatformID: "make", ActionKey: "trigger_scenario", Name: "Trigger Scenario", Description: "Trigger a Make scenario via webhook", WhenToUse: "When user asks to run a Make scenario, trigger an Integromat workflow, or call a Make webhook", Method: "POST", Path: "/connect/actions/run", Params: j(`{"webhook_url":{"type":"string","required":true,"desc":"Make webhook URL"},"data":{"type":"object","required":false,"desc":"Payload data as key-value pairs"}}`), ResponseDesc: "Scenario execution confirmation", ExecutionBackend: "pipedream", PipedreamActionID: "make-trigger-scenario"},

		// n8n
		{PlatformID: "n8n", ActionKey: "trigger_workflow", Name: "Trigger Workflow", Description: "Trigger an n8n workflow via webhook", WhenToUse: "When user asks to run an n8n workflow, trigger an n8n automation, or call an n8n webhook", Method: "POST", Path: "/connect/actions/run", Params: j(`{"webhook_url":{"type":"string","required":true,"desc":"n8n webhook URL"},"data":{"type":"object","required":false,"desc":"Payload data as key-value pairs"}}`), ResponseDesc: "Workflow execution confirmation", ExecutionBackend: "pipedream", PipedreamActionID: "n8n-trigger-workflow"},

		// Webflow
		{PlatformID: "webflow", ActionKey: "create_item", Name: "Create Item", Description: "Create a CMS collection item in Webflow", WhenToUse: "When user asks to add content to Webflow, create a CMS item, or add a blog post to Webflow", Method: "POST", Path: "/connect/actions/run", Params: j(`{"collection_id":{"type":"string","required":true,"desc":"Collection ID"},"fields":{"type":"object","required":true,"desc":"Item fields as key-value pairs including name and slug"}}`), ResponseDesc: "Item ID", ExecutionBackend: "pipedream", PipedreamActionID: "webflow-create-collection-item"},
		{PlatformID: "webflow", ActionKey: "update_item", Name: "Update Item", Description: "Update a CMS collection item in Webflow", WhenToUse: "When user asks to edit Webflow content, update a CMS item, or modify a Webflow page", Method: "POST", Path: "/connect/actions/run", Params: j(`{"collection_id":{"type":"string","required":true,"desc":"Collection ID"},"item_id":{"type":"string","required":true,"desc":"Item ID to update"},"fields":{"type":"object","required":true,"desc":"Fields to update as key-value pairs"}}`), ResponseDesc: "Updated item", ExecutionBackend: "pipedream", PipedreamActionID: "webflow-update-collection-item"},
		{PlatformID: "webflow", ActionKey: "list_items", Name: "List Items", Description: "List CMS collection items in Webflow", WhenToUse: "When user asks to see Webflow content, list CMS items, or browse a Webflow collection", Method: "POST", Path: "/connect/actions/run", Params: j(`{"collection_id":{"type":"string","required":true,"desc":"Collection ID"},"limit":{"type":"number","required":false,"desc":"Max items, default 100"}}`), ResponseDesc: "Array of collection items", ExecutionBackend: "pipedream", PipedreamActionID: "webflow-list-collection-items"},

		// Contentful
		{PlatformID: "contentful", ActionKey: "create_entry", Name: "Create Entry", Description: "Create a content entry in Contentful", WhenToUse: "When user asks to create content in Contentful, add an entry, or write a Contentful article", Method: "POST", Path: "/connect/actions/run", Params: j(`{"space_id":{"type":"string","required":true,"desc":"Contentful space ID"},"environment":{"type":"string","required":false,"desc":"Environment, default master"},"content_type":{"type":"string","required":true,"desc":"Content type ID"},"fields":{"type":"object","required":true,"desc":"Entry fields with locale keys"}}`), ResponseDesc: "Entry ID and version", ExecutionBackend: "pipedream", PipedreamActionID: "contentful-create-entry"},
		{PlatformID: "contentful", ActionKey: "update_entry", Name: "Update Entry", Description: "Update a content entry in Contentful", WhenToUse: "When user asks to edit Contentful content, update an entry, or modify a Contentful article", Method: "POST", Path: "/connect/actions/run", Params: j(`{"space_id":{"type":"string","required":true,"desc":"Contentful space ID"},"entry_id":{"type":"string","required":true,"desc":"Entry ID"},"fields":{"type":"object","required":true,"desc":"Fields to update with locale keys"}}`), ResponseDesc: "Updated entry version", ExecutionBackend: "pipedream", PipedreamActionID: "contentful-update-entry"},
		{PlatformID: "contentful", ActionKey: "publish_entry", Name: "Publish Entry", Description: "Publish a Contentful entry", WhenToUse: "When user asks to publish content in Contentful or make an entry live", Method: "POST", Path: "/connect/actions/run", Params: j(`{"space_id":{"type":"string","required":true,"desc":"Contentful space ID"},"entry_id":{"type":"string","required":true,"desc":"Entry ID to publish"},"version":{"type":"number","required":true,"desc":"Current entry version number"}}`), ResponseDesc: "Published entry details", ExecutionBackend: "pipedream", PipedreamActionID: "contentful-publish-entry"},

		// Google Search Console
		{PlatformID: "google-search-console", ActionKey: "search_analytics", Name: "Search Analytics", Description: "Get search performance data from Google Search Console", WhenToUse: "When user asks about search rankings, impressions, clicks, CTR, or SEO performance", Method: "POST", Path: "/connect/actions/run", Params: j(`{"site_url":{"type":"string","required":true,"desc":"Site URL (e.g. https://example.com/)"},"start_date":{"type":"string","required":true,"desc":"Start date YYYY-MM-DD"},"end_date":{"type":"string","required":true,"desc":"End date YYYY-MM-DD"},"dimensions":{"type":"array","required":false,"desc":"Dimensions: query, page, country, device"}}`), ResponseDesc: "Rows with clicks, impressions, CTR, position", ExecutionBackend: "pipedream", PipedreamActionID: "google_search_console-search-analytics"},
		{PlatformID: "google-search-console", ActionKey: "list_sitemaps", Name: "List Sitemaps", Description: "List submitted sitemaps in Search Console", WhenToUse: "When user asks about sitemaps, indexing status, or site structure in Search Console", Method: "POST", Path: "/connect/actions/run", Params: j(`{"site_url":{"type":"string","required":true,"desc":"Site URL"}}`), ResponseDesc: "Array of sitemaps with status and last download date", ExecutionBackend: "pipedream", PipedreamActionID: "google_search_console-list-sitemaps"},
		{PlatformID: "google-search-console", ActionKey: "inspect_url", Name: "Inspect URL", Description: "Check indexing status of a specific URL", WhenToUse: "When user asks if a page is indexed, check URL status, or inspect a page in Search Console", Method: "POST", Path: "/connect/actions/run", Params: j(`{"site_url":{"type":"string","required":true,"desc":"Site URL"},"inspection_url":{"type":"string","required":true,"desc":"URL to inspect"}}`), ResponseDesc: "Indexing status, last crawl date, and any issues", ExecutionBackend: "pipedream", PipedreamActionID: "google_search_console-inspect-url"},
	}

	for _, p := range platforms {
		if err := ks.UpsertPlatform(ctx, p); err != nil {
			slog.Warn("seed.top_platform_failed", "id", p.ID, "error", err)
		}
	}
	for _, a := range actions {
		if err := ks.UpsertAction(ctx, a); err != nil {
			slog.Warn("seed.top_action_failed", "platform", a.PlatformID, "action", a.ActionKey, "error", err)
		}
	}
	slog.Info("seed.top_connectors_complete", "platforms", len(platforms), "actions", len(actions))
}
