// Copyright 2026 Qorven AI. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0 (ELv2)
// that can be found in the LICENSE file.

package tools

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// QorvenReport generates structured reports, briefings, and visual outputs.
type QorvenReport struct{}

func NewQorvenReport() *QorvenReport { return &QorvenReport{} }

func (t *QorvenReport) Name() string { return "qorven_report" }
func (t *QorvenReport) Description() string {
	return "Generate structured reports and visual outputs. Formats: briefing, comparison, timeline, slides, table."
}
func (t *QorvenReport) Parameters() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"format": map[string]any{"type": "string", "enum": []string{"briefing", "comparison", "timeline", "table", "slides"}, "description": "Output format"},
			"title":  map[string]any{"type": "string", "description": "Report title"},
			"data":   map[string]any{"type": "string", "description": "Data/content to format"},
			"items":  map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Items to compare or list"},
		},
		"required": []string{"format", "title"},
	}
}

func (t *QorvenReport) Execute(ctx context.Context, args map[string]any) *Result {
	format, _ := args["format"].(string)
	title, _ := args["title"].(string)
	data, _ := args["data"].(string)
	items, _ := args["items"].([]any)

	var itemStrs []string
	for _, item := range items {
		if s, ok := item.(string); ok {
			itemStrs = append(itemStrs, s)
		}
	}

	switch format {
	case "briefing":
		return TextResult(t.briefing(title, data))
	case "comparison":
		return TextResult(t.comparison(title, itemStrs, data))
	case "timeline":
		return TextResult(t.timeline(title, itemStrs))
	case "table":
		return TextResult(t.table(title, itemStrs, data))
	case "slides":
		return TextResult(t.slides(title, itemStrs, data))
	default:
		return ErrorResult("unknown format: " + format)
	}
}

func (t *QorvenReport) briefing(title, data string) string {
	return fmt.Sprintf(`# Executive Briefing: %s

**Date:** %s
**Classification:** Internal

---

## Current State
%s

## Key Tensions
_[To be filled based on analysis]_

## Open Questions
_[To be filled based on analysis]_

## Recommended Next Steps
1. _[Action item 1]_
2. _[Action item 2]_
3. _[Action item 3]_

---
_Generated by Qorven Report Engine_`, title, time.Now().Format("January 2, 2006"), data)
}

func (t *QorvenReport) comparison(title string, items []string, data string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Comparison: %s\n\n", title))
	sb.WriteString("| Feature |")
	for _, item := range items {
		sb.WriteString(fmt.Sprintf(" %s |", item))
	}
	sb.WriteString("\n|---|")
	for range items {
		sb.WriteString("---|")
	}
	sb.WriteString("\n")
	// Add placeholder rows
	for _, feature := range []string{"Performance", "Cost", "Ease of Use", "Scalability", "Community"} {
		sb.WriteString(fmt.Sprintf("| %s |", feature))
		for range items {
			sb.WriteString(" - |")
		}
		sb.WriteString("\n")
	}
	if data != "" {
		sb.WriteString(fmt.Sprintf("\n## Notes\n%s\n", data))
	}
	return sb.String()
}

func (t *QorvenReport) timeline(title string, events []string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Timeline: %s\n\n", title))
	for i, event := range events {
		sb.WriteString(fmt.Sprintf("### %d. %s\n\n", i+1, event))
	}
	return sb.String()
}

func (t *QorvenReport) table(title string, rows []string, headers string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s\n\n", title))
	if headers != "" {
		cols := strings.Split(headers, ",")
		sb.WriteString("|")
		for _, c := range cols {
			sb.WriteString(fmt.Sprintf(" %s |", strings.TrimSpace(c)))
		}
		sb.WriteString("\n|")
		for range cols {
			sb.WriteString("---|")
		}
		sb.WriteString("\n")
	}
	for _, row := range rows {
		sb.WriteString(fmt.Sprintf("| %s |\n", row))
	}
	return sb.String()
}

func (t *QorvenReport) slides(title string, slides []string, data string) string {
	var sb strings.Builder
	// Marp format
	sb.WriteString("---\nmarp: true\ntheme: default\npaginate: true\n---\n\n")
	sb.WriteString(fmt.Sprintf("# %s\n\n%s\n\n---\n\n", title, time.Now().Format("January 2, 2006")))
	for i, slide := range slides {
		sb.WriteString(fmt.Sprintf("# Slide %d\n\n%s\n\n---\n\n", i+1, slide))
	}
	if data != "" {
		sb.WriteString(fmt.Sprintf("# Summary\n\n%s\n\n---\n\n", data))
	}
	sb.WriteString("# Thank You\n\n_Generated by Qorven_\n")
	return sb.String()
}
