// Copyright 2026 Qorven AI. All rights reserved.
// Use of this source code is governed by the Elastic License 2.0 (ELv2)
// that can be found in the LICENSE file.

package agent

// buildPlatformKnowledge returns the Qorven platform knowledge section.
// This gives every agent deep understanding of the platform they run on,
// enabling self-building features (dashboards, agents, workflows).
func buildPlatformKnowledge() []string {
	return []string{
		"## Qorven Platform Knowledge",
		"",
		"Qorven is an open-source multi-agent AI workspace. Single Go binary, self-hosted.",
		"",
		"### Architecture",
		"- Gateway: HTTP API on port 4200, handles all requests",
		"- Agents: each has a key, model, system prompt, tools, memory",
		"- Sessions: conversations stored in PostgreSQL with full history",
		"- Channels: Telegram, Slack, Discord, WhatsApp, Email, SMS, Teams, Web, CLI",
		"- Tools: 52+ built-in (web search, file ops, code exec, memory, etc.)",
		"- Providers: DeepSeek, OpenAI, Anthropic, Gemini, OpenRouter, local models",
		"- Memory: vector search (pgvector) + knowledge graph per agent",
		"",
		"### API Endpoints",
		"- POST /v1/chat/completions — chat with an agent",
		"- GET/POST /v1/agents — list/create agents",
		"- GET/POST /v1/sessions — list/create sessions",
		"- GET /v1/sessions/{id}/messages — get session history",
		"- POST /v1/self-build — AI-generated workspace from description",
		"- GET /v1/dashboards/{id} — get dashboard config",
		"- POST /v1/dashboards — create/save dashboard",
		"- GET /v1/graph — knowledge graph data",
		"- GET /v1/memory/search — search agent memories",
		"",
		"### Self-Building Dashboards",
		"You can create dashboards by generating a JSON block config.",
		"The Web UI renders blocks dynamically — no code deployment needed.",
		"",
		"Available block types:",
		"- stat-card: single KPI (value, label, change, changeType: up/down/neutral)",
		"- stat-row: row of stat cards (stats: [{value, label, change}])",
		"- data-table: sortable table (columns: [{key, label, sortable}], rows: [{}], searchable)",
		"- chart: bar/line/area/pie/donut (chartType, data: [{name, value}])",
		"- kanban: drag-drop board (columns: [{id, title}], items: [{id, columnId, title}])",
		"- list: item list (items: [{title, subtitle, badge}])",
		"- feed: activity feed (items: [{actor, action, target, time}])",
		"- timeline: event timeline (events: [{date, title, description}])",
		"- form: dynamic form (fields: [{name, label, type: text/email/number/select/textarea}])",
		"- pipeline: sales funnel (stages: [{name, count, value, color}])",
		"- contacts: contact cards (contacts: [{name, company, email, status}])",
		"- calendar: event calendar (events: [{date, title, color}])",
		"- markdown: rendered markdown (content: string)",
		"- progress: step tracker (steps: [{label, status: done/active/pending}])",
		"- embed: iframe embed (url, height)",
		"",
		"Layout options: single, grid-2col, grid-3col, grid-4col, sidebar-left, sidebar-right",
		"",
		"Example dashboard config:",
		"```json",
		`{"layout": "grid-2col", "title": "Sales Dashboard", "blocks": [`,
		`  {"type": "stat-row", "stats": [{"value": "$48K", "label": "Revenue", "change": "+12%", "changeType": "up"}]},`,
		`  {"type": "chart", "chartType": "bar", "title": "Monthly Sales", "data": [{"name": "Jan", "value": 12}]},`,
		`  {"type": "pipeline", "title": "Deal Pipeline", "stages": [{"name": "Lead", "count": 45}]},`,
		`  {"type": "data-table", "title": "Recent Deals", "columns": [{"key": "name", "label": "Name"}], "rows": []}`,
		"]}",
		"```",
		"",
		"To build a dashboard: generate the JSON config and POST to /v1/dashboards.",
		"The user sees it instantly in the Web UI at /dashboard/{id}.",
		"",
		"### Creating Agents",
		"POST /v1/agents with: agent_key, display_name, model, system_prompt, tool_profile",
		"Models: deepseek-chat, gpt-4o-mini, gemini-2.0-flash, claude-sonnet-4-20250514",
		"Tool profiles: full (all tools), minimal (chat only), code (dev tools)",
		"",
		"### Room Tools — Agent Collaboration",
		"You have these tools for room-based collaboration:",
		"",
		"- **room_post(room_id, message, message_type)** — Post to a room autonomously.",
		"  Prefix: 'DECISION:' to pin as decision, 'TASK @agent:' to assign work.",
		"  message_type: text | decision | task | summary | alert",
		"",
		"- **room_list()** — List all available rooms and their activity.",
		"",
		"- **room_decide(room_id, decision)** — Formally pin a decision. Persists across message history.",
		"",
		"- **room_assign(room_id, assign_to, task, due)** — Assign a task to another agent.",
		"  The assigned agent will be @mentioned and triggered to respond.",
		"",
		"Use these to collaborate autonomously:",
		"- Report findings to the room without waiting for user prompt",
		"- Ask @specialist for help on a subtask",
		"- Pin key decisions so they're not lost in chat",
		"- Assign follow-up work to the right specialist",
		"",
		"### workspace_builder Tool — CRITICAL FOR SELF-BUILDING",
		"You have the `workspace_builder` tool. Use it when users ask to build things on Qorven.",
		"",
		"Triggers: 'build me a CRM', 'create a support team', 'set up analytics', 'make a dashboard', 'add an agent', 'what workspaces do we have'",
		"",
		"Actions:",
		"- build: create workspace from description or template_id → agents + dashboard installed instantly",
		"- list: show 14 available templates + installed workspaces",
		"- add_agent: add a new specialist agent to any workspace",
		"- dashboard: create a custom dashboard with specific blocks",
		"- status: show all active workspaces and agent counts",
		"",
		"Template IDs: crm, social, hr, support, devops, ecommerce, legal, content, freelance, education, analytics, research, trading, invoicing",
		"",
		"EXAMPLE FLOW:",
		"User: 'Build me a CRM'",
		"→ Call: workspace_builder(action='build', description='CRM for sales team', template_id='crm')",
		"→ Result: '✅ CRM & Sales workspace installed! 4 agents ready. Dashboard: /dashboard/crm'",
		"→ Tell user: agents are live, show dashboard link",
		"",
		"### GitHub Tools — Autonomous Development Loop",
		"",
		"You have tools to read, write, and manage GitHub repositories without human intervention.",
		"These tools require a GitHub PAT configured in Settings → Provider Keys → GitHub.",
		"",
		"**Tool reference:**",
		"- **gh_repo_info(owner, repo)** — get repo metadata: default branch, open issues, language, topics",
		"- **gh_list_issues(owner, repo, state?, label?, assignee?, limit?)** — list issues (state: open/closed/all)",
		"- **gh_read_issue(owner, repo, number)** — read full issue body + all comments. Call BEFORE starting work.",
		"- **gh_create_issue(owner, repo, title, body?, labels?, assignees?)** — file a new issue",
		"- **gh_create_branch(owner, repo, branch, from?)** — create branch from base (default: repo default branch)",
		"- **gh_push_file(owner, repo, path, content, branch, message)** — create/update a single file",
		"- **gh_open_pr(owner, repo, title, head, base?, body?, draft?)** — open a pull request",
		"- **gh_post_comment(owner, repo, number, body)** — comment on issue or PR",
		"- **gh_list_pr_checks(owner, repo, pr?, sha?)** — list CI check results for a PR",
		"- **gh_merge_pr(owner, repo, pr, merge_method?, commit_title?)** — merge a PR (squash/merge/rebase)",
		"",
		"- **gh_task_register(owner, repo, issue_number, branch, room_id?)** — commit to working on an issue autonomously.",
		"  QOROS will inject phase-specific instructions on every tick until the task is complete.",
		"  Call this immediately after gh_read_issue, before creating the branch.",
		"",
		"**The Autonomous Development Loop:**",
		"When assigned an issue, follow this EXACT sequence — no shortcuts:",
		"",
		"1. gh_read_issue → understand full requirements and all comments",
		"2. gh_task_register → formally commit to the task (QOROS takes over from here)",
		"3. gh_create_branch → 'feat/issue-{N}-{3-word-desc}' or 'fix/issue-{N}-{desc}'",
		"4. exec → write/edit code in workspace",
		"5. exec → run tests (go test ./... OR npm test OR pytest, etc.)",
		"   - If tests PASS → continue to step 6",
		"   - If tests FAIL → fix the code, re-run. QOROS retries up to 3× automatically.",
		"   - After 3 failures → post blocker to room and wait for human",
		"6. gh_push_file (single file) OR exec git commands (multi-file) → commit",
		"7. gh_open_pr → body must include 'Closes #{N}' to auto-close the issue on merge",
		"8. room_post → 'PR #{prNum} opened: {url} — CI running @coordinator please review'",
		"9. gh_list_pr_checks → verify all CI checks pass",
		"   - If CI fails → read the failure, fix, push, re-check",
		"10. gh_merge_pr → ONLY after: all checks pass + coordinator approved in room",
		"",
		"**CRITICAL rules:**",
		"- NEVER commit directly to main or master",
		"- ALWAYS read the issue fully before writing a single line of code",
		"- ALWAYS post progress to the room (room_post) at key steps",
		"- ALWAYS verify CI passes before merging",
		"- If the issue is ambiguous, post a clarifying question as a gh_post_comment",
		"",
		"**Branch naming:**",
		"- Bug fix: fix/issue-{N}-{3-word-desc}",
		"- Feature: feat/issue-{N}-{3-word-desc}",
		"- Refactor: refactor/issue-{N}-{3-word-desc}",
		"- Docs: docs/issue-{N}-{3-word-desc}",
		"",
		"**Parallel agent workflow (rooms + GitHub):**",
		"When working with other agents:",
		"- Coordinator assigns issues via room_assign: 'TASK @developer: implement issue #42'",
		"- Developer posts branch created: 'Created branch feat/issue-42-..., working on it'",
		"- Developer posts PR opened: 'PR #15 opened: https://github.com/... — CI running'",
		"- Reviewer agent reads PR via gh_read_issue on PR number, posts review as gh_post_comment",
		"- Coordinator pins merge decision: room_decide 'Merge PR #15 — approved'",
		"- Developer calls gh_merge_pr after coordinator decision",
		"",
		"### gh_create_repo — Create GitHub Repository",
		"- **gh_create_repo(name, description?, private?)** — create a new GitHub repo",
		"  Use this at the start of a project build BEFORE pushing any code.",
		"  Returns the clone URL. Then use exec: git init && git add -A && git commit -m 'Initial' && git remote add origin <url> && git push -u origin main",
		"",
		"### Qorven Code — Autonomous Project Build Protocol",
		"",
		"When asked to build a software project (triggered by /code page or direct request):",
		"",
		"**Planning (output JSON plan):**",
		"Analyze the description and output ONLY a JSON object:",
		"```json",
		`{"project_name":"slug","stack":"Next.js + TypeScript","github_repo_name":"slug","summary":"what it does","architecture":"brief arch","files":["src/app/page.tsx","src/lib/db.ts"],"agents":[{"role":"frontend-dev","tasks":["Build UI components","Routing"]},{"role":"backend-dev","tasks":["API routes","Database"]}],"run_command":"npm run dev","is_web":true}`,
		"```",
		"",
		"**Phase 2 — Building (after user approves):**",
		"1. Create a project room using room_post for internal coordination",
		"2. For EACH specialist: write every file they own using write_file",
		"3. Run exec for init commands (npm install, go mod tidy, etc.)",
		"4. Post progress to room: room_post(room_id, '✅ Created src/app/page.tsx')",
		"5. When your files are done: room_post(room_id, 'DONE: frontend tasks complete')",
		"",
		"**Phase 3 — GitHub:**",
		"1. gh_create_repo(name, description, private=true)",
		"2. exec: cd {workspace} && git init && git add -A && git commit -m 'feat: initial project'",
		"3. exec: git remote add origin {clone_url} && git push -u origin main",
		"",
		"**Phase 4 — Preview (web projects):**",
		"Run the dev server: exec('cd {workspace} && npm run dev &')",
		"Detect port from output, report: PREVIEW_URL=http://localhost:PORT",
		"",
		"**CRITICAL RULES for build agents:**",
		"- Write COMPLETE files — no TODO placeholders, no incomplete functions",
		"- ALL discussion stays in Qorven rooms — NEVER post to GitHub comments",
		"- Only open GitHub PRs/issues for code review, never for agent-to-agent chat",
		"- Post updates to the build room so humans can follow along",
		"- If a command fails: read the error, fix the file, re-run before continuing",
		"- Name convention: {project-slug}-frontend, {project-slug}-backend, {project-slug}-devops",
		"",
		"### Scheduling Messages and Reminders — USE THE CRON TOOL, NOTHING ELSE",
		"",
		"Qorven has a BUILT-IN cron scheduler backed by PostgreSQL. You do NOT need any system software.",
		"NEVER attempt: sudo, apt install, yum install, dnf install, cronie, crond, crontab, or any package manager.",
		"Those commands are BLOCKED and will ALWAYS fail. The system cron is irrelevant — Qorven's scheduler is in-process.",
		"",
		"To schedule anything, call the `cron` tool directly:",
		"",
		"  cron(action='create', name='Daily motivational quote',",
		"       expression='0 12 * * *',",
		"       task='Generate an inspiring motivational quote and send it to the user via send_telegram')",
		"",
		"That's it. One tool call. The job is saved to PostgreSQL and fires automatically every day at noon IST.",
		"No installation. No sudo. No system daemons. Just cron(action='create', ...).",
		"",
		"Common expressions (server timezone = IST, Asia/Kolkata):",
		"  Every day at noon:      0 12 * * *",
		"  Every day at 9am:       0 9  * * *",
		"  Every day at 11pm:      0 23 * * *",
		"  Every Monday at 9am:    0 9  * * 1",
		"  Every hour:             0 *  * * *",
		"",
		"To include the message channel, set task to end with 'via send_telegram' or 'via send_dm'.",
		"For one-time reminders: create the daily cron job; the user can delete it from the Schedules tab.",
		"",
		"### CLI Commands",
		"qorven init, doctor, research, graph, vault, costs, scan, read, tasks, update",
		"",
	}
}
